jellyfin/jellyfin-sdk-kotlin

android/src/main/java/mediabrowser/apiinteraction/IConnectionManager.java, android/src/main/java/mediabrowser/apiinteraction/connect/ConnectService.java, android/src/main/java/mediabrowser/apiinteraction/connectionmanager/ConnectionManager.java
:unlock: Unlock all the things!
=> Remove registration check for features

android/src/main/java/mediabrowser/apiinteraction/ApiClient.java, android/src/main/java/mediabrowser/model/entities/ChapterInfo.java, android/src/main/java/mediabrowser/model/entities/PersonType.java, android/src/main/java/mediabrowser/model/querying/ItemSortBy.java
* Restores deleted models used in Android TV app
* Fixes `NullPointerException` when reporting playback stopped
=> Android TV Support

android/src/main/java/mediabrowser/apiinteraction/discovery/ServerLocator.java
Use "who is JellyfinServer?" instead of "who is EmbyServer?" for autodiscovery.
=> Update autodiscovery message

android/src/main/java/mediabrowser/apiinteraction/android/AndroidDevice.java
* Add support for pulling the user set device name from `Settings.Global` in favor of the device's model name.
* Add check for null `Cursor` and properly close it after use.
refs: https://stackoverflow.com/a/44460486/1373956
=> Add device name from settings

library/src/main/java/org/jellyfin/apiclient/interaction/BaseApiClient.java, library/src/main/java/org/jellyfin/apiclient/interaction/connectionmanager/ConnectionManager.java
merge this one with jellyfin/jellyfin#1588
=> Remove hardcoded base url from all requests

library/src/main/java/org/jellyfin/apiclient/interaction/connectionmanager/ConnectionManager.java, library/src/main/java/org/jellyfin/apiclient/interaction/connectionmanager/FindServersInnerResponse.java, library/src/main/java/org/jellyfin/apiclient/interaction/connectionmanager/FindServersResponse.java
Cherry-picked the commit to fix the client stalling when finding servers so it can be merged separately.
=> fix stall when calling FindServers

library/build.gradle, library/src/main/java/org/jellyfin/apiclient/model/apiclient/ServerInfo.java, library/src/main/java/org/jellyfin/apiclient/model/serialization/GsonJsonSerializer.java, library/src/main/java/org/jellyfin/apiclient/model/serialization/ServerInfoDeserializer.java, library/src/test/java/org/jellyfin/apiclient/model/serialization/ServerInfoDeserializerTest.java
* Moves `GsonJsonSerializer` to the `model.serialization` package
* Adds a `Version` field to `ServerInfo` and fixes formatting issues
* Adds a custom deserializer (with tests) to migrate `ServerInfo` address fields
=> GsonJsonSerializer updates

android/build.gradle
New version release is needed to get ATV 0.11.0 out.
=> Update version to 0.5.0

library/src/main/java/org/jellyfin/apiclient/interaction/ApiClient.java, library/src/main/java/org/jellyfin/apiclient/interaction/discovery/ServerLocator.java, library/src/main/java/org/jellyfin/apiclient/interaction/websocket/ApiWebSocket.java
Basically here as well, people did not understand what a format string is and that in some cases incorrect concatenation leads to a format string injection. This hopefully fixes all of them.
=> Fix incorrect usages of ILogger interface here as well

library/src/main/java/org/jellyfin/apiclient/model/dto/BaseItemDto.java, library/src/main/java/org/jellyfin/apiclient/model/dto/GenreDto.java
Needed for details redesign because the array doesn't have id's
=> Add genre items and deprecate the genres string array

library/src/main/java/org/jellyfin/apiclient/interaction/connectionmanager/ConnectionManager.java, library/src/main/java/org/jellyfin/apiclient/interaction/connectionmanager/FindServersInnerResponse.java, library/src/test/java/org/jellyfin/apiclient/interaction/connectionmanager/ConnectionManagerTest.java
Changes:
- Formatted the files I worked on (includes import cleaning)
- Try multiple server urls in the connect function
- The `NormalizeAddress` now trims the input
- The `NormalizeAddress` now properly detects if a protocol is set
- The `NormalizeAddress` can return multiple urls (Could add a default port too in the future)
- The `ServerLocator` now doesn't normalize because the connect function does that already..
Tested both manual input and server detection to work properly.
=> Try both https and http when no protocol is set

build.gradle.kts, library/build.gradle.kts
No breaking changes in this one
=> Upgrade dependencies

android/build.gradle.kts, gradle.properties
I expected the "upgrade to androidx" thing to be harder lol, apparently the dependency wasn't used at all!
=> Remove appcompat

README.md
=> Update header of README

android/build.gradle, library/src/main/java/org/jellyfin/apiclient/model/dto/BaseItemPerson.java
This PR fixes a NPE when the type of a person is set to null. I also bumped the version and targetted  the release branch.
Will add the fix to the master branch later.
=> Fix crash when person type is null

README.md, android/src/main/java/org/jellyfin/apiclient/JellyfinAndroid.kt, android/src/main/java/org/jellyfin/apiclient/interaction/AndroidDevice.kt, library/src/main/java/org/jellyfin/apiclient/AppInfo.kt, library/src/main/java/org/jellyfin/apiclient/DiscoveryService.kt, library/src/main/java/org/jellyfin/apiclient/Jellyfin.kt, library/src/main/java/org/jellyfin/apiclient/JellyfinOptions.kt, library/src/main/java/org/jellyfin/apiclient/NoHttpClient.kt, library/src/main/java/org/jellyfin/apiclient/interaction/ApiClient.java, library/src/main/java/org/jellyfin/apiclient/interaction/BaseApiClient.java
I think I was still working on something on this branch but I forgot what is was and the code looks good to me.
=> Add Jellyfin class which should be used when using the library

library/src/main/java/org/jellyfin/apiclient/interaction/ApiClient.java, samples/kotlin-console/src/main/kotlin/org/jellyfin/sample/console/utils/GarbageHttpClient.kt
Confirmed working with sample client auth
=> Use JSON instead of forms (master branch)

library/src/main/java/org/jellyfin/apiclient/Jellyfin.kt, library/src/main/java/org/jellyfin/apiclient/interaction/BaseApiClient.java
Needed for ATV app which will initialize the apiclient when the app starts but adds the server address in the startupactivity using ChangeServerLocation.
=> Make server address optional

azure-pipelines.yml
I'm not sure if this fixes the issue but I think it should.
Closes #86
=> Fix assets not uploaded on release

azure-pipelines.yml
=> Fix GitHub release assets again

model/build.gradle.kts
Part **2** of multiple
Merge after #92
=> Update model module to support generated sources

android/build.gradle.kts, android/proguard-rules.pro
Fixes jellyfin/android#116 and jellyfin/android#119
After approved and merged I will cherrypick it into the release branch and tag it. I'll then open a PR in jellyfin/android to update the version and add dependency substitution code (which is really useful to test your local apiclient clone with the app).
=> Add proguard configuration to android module

openapi-generator/README.md, samples/kotlin-console/README.md
Fixed all the current markdown issues. If the readme's change in the future we can strictly enforce the linter.
=> Fix all markdown linter issues

library/src/main/java/org/jellyfin/apiclient/discovery/LocalServerDiscovery.kt
This fixes an issue reporting in our Matrix channels where the new Android app crashes on https://grapheneos.org. If approved I'll backport the try-catch statement to 0.7.x (I'll push it to the release branch).
=> Catch IO exceptions when sending discovery messages

jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/KtorClient.kt, jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/Response.kt, jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/compatibility/JavaDataCallback.kt, samples/kotlin-console/src/main/kotlin/org/jellyfin/sample/console/cli/Libraries.kt
Let me know if something is missing.
It uses infix functions because pretty code.
=> Add more information to the Response class

buildSrc/src/main/kotlin/Dependencies.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/AudioApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/ConfigurationApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/DlnaServerApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/DynamicHlsApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/HlsSegmentApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/ImageApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/ImageByNameApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/ItemLookupApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/LibraryApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/LiveTvApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/MediaInfoApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/RemoteImageApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/SubtitleApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/UniversalAudioApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/VideoAttachmentsApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/VideoHlsApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/VideosApi.kt, openapi-generator/build.gradle.kts, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiReturnTypeBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiTypeBuilder.kt
I wasn't sure if the ByteReadChannel class would be exposed properly (since ktor is implementation, not api) but from my quick testing it seems like it does.
=> Use coroutine based ByteReadChannel instead of synchronous InputStream

buildSrc/src/main/kotlin/Dependencies.kt, jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/sockets/WebSocketApi.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/AppInfo.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/Jellyfin.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/AddressCandidateHelper.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/DiscoveryService.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/LocalServerDiscovery.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/RecommendedServerDiscovery.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/RecommendedServerInfo.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/RecommendedServerInfoScore.kt, jellyfin-core/src/test/kotlin/org/jellyfin/apiclient/discovery/DiscoveryServiceTests.kt, jellyfin-model/src/main/kotlin/org/jellyfin/apiclient/model/discovery/ServerVersion.kt, jellyfin-model/src/test/kotlin/org/jellyfin/apiclient/model/discovery/ServerVersionTests.kt, samples/kotlin-console/build.gradle.kts, samples/kotlin-console/src/main/kotlin/org/jellyfin/sample/console/cli/Ping.kt
to find the best server candidate from a given input.
Closes #101
=> Add recommended server discovery

buildSrc/src/main/kotlin/Dependencies.kt, samples/kotlin-cli/README.md, samples/kotlin-cli/build.gradle.kts, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/Main.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/Options.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Discover.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Libraries.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Login.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Ping.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Users.kt, samples/kotlin-cli/test.sh, settings.gradle.kts
Name change: kotlin-console -> kotlin-cli
Library change: kotlinx.cli -> Clikt
Now supports JELLYFIN_SERVER and JELLYFIN_TOKEN environment variables
=> Refactor CLI sample

.gitattributes
[Documentation](https://github.com/github/linguist#overrides)
Thanks to @MrTimscampi for sharing the docs.
=> Update gitattributes to mark generated code as such

README.md
**Description**
Unfortunately I cannot really help with these points:
* The sample code is outdated.
* Should add a link to the sample(s)
However, I can help with the other two, so I opened this :wink:  
**Changes**
* update readme title
* update readme badges
* update readme headline hierarchy
* add `Reference Use-Cases` blurb to the end of readme
**Issues**
*  part of #107
=> Initial readme update

jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/KtorClient.kt
Before this fix a list would be encoded as `[]` for empty and `[1, 2, 3]` for filled. Now it will be ignored when empty and `1,2,3` when filled.
I've also added logging for requests.
=> Fix lists incorrectly encoded in urls

jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/AddressCandidateHelper.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/DiscoveryService.kt
Tested in the jellyfin-android apiclient-1.0 branch.
- Fix getRecommendedServer not returning
- Improve address candidate prioritization order
=> Discovery fixes

jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/PackageApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/UserApi.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationBuilder.kt
Although both of the functions that use them are incorrect.
=> Support nullable POST bodies

jellyfin-platform-android/build.gradle.kts, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/Main.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Observe.kt
Also removed unused and deprecated `kotlin-android-extensions` plugin from the android module.
=> Add "observe" command to CLI sample to listen for WebSocket messages

jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/ApiClient.kt, jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/KtorClient.kt, jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/sockets/WebSocketApi.kt
- Add more properties to ApiClient interface
- Use ApiClient interface instead of KtorApiClient in WebSocketApi
=> Add more properties to apiclient interface

jellyfin-api/src/main/kotlin-generated/org/jellyfin/sdk/api/info/ApiConstants.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/Jellyfin.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiConstantsBuilder.kt
Server version is not put into the api version constant.
=> Remove server version from constants

jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/sockets/WebSocketApi.kt
Might rewrite it to use polymorphism for sdk1.1.
=> Use SessionMessageType enum in WebSocketApi

.github/workflows/sdk-test.yaml
Now that we've updated to Gradle 7 it should work
Replacement for #200
=> Use Java 16 in tests

.github/workflows/sdk-update-api-spec.yaml
* update workflow name
* change to overwrite generated PR_BODY to prevent character overflow
=> fix generated PR body overflow

jellyfin-core/api/jellyfin-core.api, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/Jellyfin.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/DiscoveryService.kt, jellyfin-model/src/main/kotlin/org/jellyfin/sdk/model/ClientInfo.kt, jellyfin-model/src/main/kotlin/org/jellyfin/sdk/model/DeviceInfo.kt
- Add deviceInfo and clientInfo getters in Jellyfin class
- More/improved docs
=> Add deviceInfo and clientInfo getters in Jellyfin class

.github/workflows/merge-conflict-labeler.yaml
Old one wasn't maintained anymore
=> Use eps1lon/actions-label-merge-conflict

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, gradle/libs.versions.toml
- Use Maven version of Koin
- Remove jcenter repository
=> Remove jcenter repository

buildSrc/src/main/kotlin/Dependencies.kt, gradle/libs.versions.toml, jellyfin-model/src/main/kotlin-generated/org/jellyfin/sdk/model/api/HttpHeaderInfo.kt, jellyfin-model/src/main/kotlin-generated/org/jellyfin/sdk/model/api/LocalizationOption.kt, jellyfin-model/src/main/kotlin-generated/org/jellyfin/sdk/model/api/NameValuePair.kt, jellyfin-model/src/main/kotlin-generated/org/jellyfin/sdk/model/api/ParentalRating.kt, jellyfin-model/src/main/kotlin-generated/org/jellyfin/sdk/model/api/ProfileCondition.kt, jellyfin-model/src/main/kotlin-generated/org/jellyfin/sdk/model/api/XmlAttribute.kt
Including kotlinx.serialization 1.20 with faster JSON encoding/decoding and a kotlinpoet update that now adds backticks for the name "value".
=> Update all dependencies to latest version

README.md, detekt.yml, gradle/libs.versions.toml, jellyfin-platform-android/build.gradle.kts
- android: Remove desugaring from the Android platform
- readme: Add information about desugaring and update sample code in README
- detekt: Increase ThrowsCount to 6
Closes #250
=>  Add information about desugaring and update sample code in README

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/MissingPathVariableError.kt, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/exception/MissingPathVariableException.kt
=> Rename MissingPathVariableError to MissingPathVariableException and extend ApiClientException

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/HttpClientOptions.kt, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/RecommendedServerDiscovery.kt
=> Add requestTimeout and socketTimeout to HttpClientOptions

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/ApiClient.kt, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/util/PathBuilder.kt, jellyfin-api/src/test/kotlin/org/jellyfin/sdk/api/client/KtorClientTests.kt, jellyfin-api/src/test/kotlin/org/jellyfin/sdk/api/client/PathBuilderTests.kt
=> Move createPath function to separate PathBuilder

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/ApiClient.kt, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/util/AuthorizationHeaderBuilder.kt, jellyfin-api/src/test/kotlin/org/jellyfin/sdk/api/client/AuthorizationHeaderBuilderTests.kt
- for easier re-use and testing
- the way the header is build was slightly changed but the added tests show that it works
- also fixed a constant
=> Move createAuthorizationHeader function to separate AuthorizationHeaderBuilder

jellyfin-model/src/main/kotlin/org/jellyfin/sdk/model/ServerVersion.kt
Required for jellyfin-androidtv
=> Add toString function to ServerVersion

samples/java-cli/build.gradle.kts, samples/java-cli/src/main/java/org/jellyfin/sample/cli/Main.java, settings.gradle.kts
It doesn't contain commands etc. but it does show how to use the API in Java. Can be extended in the future.
=> Add simplified Java version of the cli sample

jellyfin-model/api/jellyfin-model.api, jellyfin-model/src/main/kotlin-generated/org/jellyfin/sdk/model/api/BaseItemDto.kt, jellyfin-model/src/main/kotlin-generated/org/jellyfin/sdk/model/api/BaseItemPerson.kt, jellyfin-model/src/main/kotlin-generated/org/jellyfin/sdk/model/api/SeriesTimerInfoDto.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/hooks/model/ImageMapsHook.kt
=> Fix nullability in ImageMapsHook

jellyfin-api/src/main/kotlin-generated/org/jellyfin/sdk/api/operations/NotificationsApi.kt, openapi-generator/build.gradle.kts, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/CurrentUserIdDefaultValue.kt
- fix toLowerCase() -> lowercase()
- Fix DefaultUserIdHook with .toString() calls
- Fix warnings in openapi-generator build.gradle.kts
- Update generated sources
=> Fix warnings and issue in DefaultUserIdHook

buildSrc/src/main/kotlin/Dependencies.kt, gradle/libs.versions.toml
=> Update all dependencies

jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt, jellyfin-platform-android/proguard-rules.pro
Required for a fix in the Android TV app I'm working on.
=> Forward UnknownHostException and log unknown exceptions in KtorClient

jellyfin-api/src/test/kotlin/org/jellyfin/sdk/api/client/KtorClientTests.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Bitrate.kt
=> Fix all linter issues from 1.0.z release

jellyfin-platform-android/proguard-rules.pro
Credits go to @Maxr1998.
Closes jellyfin/jellyfin-android#496
=> Workaround for server connection failure on Android

build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, gradle/libs.versions.toml, jellyfin-api/build.gradle.kts, jellyfin-core/build.gradle.kts, jellyfin-model/api/jellyfin-model.api, jellyfin-model/build.gradle.kts, openapi-generator/build.gradle.kts
Also updated Kotlin to 1.5.20 which changed the serializer behavior slightly.
=> Use Gradle Dependency Catalog for plugins

gradle/libs.versions.toml
Required to fix a false-positive in #308 (detekt/detekt#3970)
=> Update Detekt to 1.18.0

README.md
=> Update README for multiplatform changes

buildSrc/src/main/kotlin/Pom.kt
I noticed our name wasn't pretty in the license dialog while playing around with Findroid. This PR changes that.
=> Set proper name in POM files

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/ApiClientException.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/InvalidContentException.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/InvalidStatusException.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/MissingPathVariableException.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/MissingUserIdException.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/TimeoutException.kt, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt
- Add cause to custom exception classes
Makes it easier to find out where exceptions come from. Depends on #322
=> Add cause to custom exception classes

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/SocketConnectionFactory.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/SocketInstance.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/SocketInstanceConnection.kt, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/sockets/OkHttpWebsocketSession.kt
The next PR should be the reconnection logic implementation... maybe
=> Rewrite/simplify internal WebSocket message sending

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/SocketInstance.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/SocketInstanceConnection.kt, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/sockets/OkHttpWebsocketSession.kt
=> Use Authorization header for WebSocket connections

docs/migration/v1.2.md
(merges to master and will be cherrypicked to 1.2 release branch after)
=> Add migration document for v1.2

build.gradle.kts, gradle/libs.versions.toml, jellyfin-api/src/commonTest/kotlin/org/jellyfin/sdk/api/client/util/ApiSerializerTests.kt, jellyfin-api/src/commonTest/kotlin/org/jellyfin/sdk/api/client/util/AuthorizationHeaderBuilderTests.kt, jellyfin-api/src/commonTest/kotlin/org/jellyfin/sdk/api/client/util/UrlBuilderTests.kt, jellyfin-core/src/jvmTest/kotlin/org/jellyfin/sdk/discovery/DiscoveryServiceTests.kt, jellyfin-model/api/jellyfin-model.api, jellyfin-model/src/commonMain/kotlin/org/jellyfin/sdk/model/ServerVersion.kt, jellyfin-model/src/commonTest/kotlin/org/jellyfin/sdk/model/discovery/ServerVersionTests.kt, jellyfin-model/src/commonTest/kotlin/org/jellyfin/sdk/model/extensions/PairExtensionTests.kt, jellyfin-model/src/jvmTest/kotlin/org/jellyfin/sdk/model/extensions/GeneralCommandMessageExtensionTests.kt, jellyfin-model/src/jvmTest/kotlin/org/jellyfin/sdk/model/extensions/PairExtensionTestsJvm.kt, jellyfin-model/src/jvmTest/kotlin/org/jellyfin/sdk/model/serializer/DateTimeSerializerTests.kt, jellyfin-model/src/jvmTest/kotlin/org/jellyfin/sdk/model/serializer/UUIDSerializerTests.kt, openapi-generator/src/test/kotlin/org/jellyfin/openapi/builder/api/ApiNameBuilderTests.kt, testutils/build.gradle.kts
- Use kotest framework
- Use kotest assertions
- Add Comparable<ServerVersion> to ServerVersion
=> Migrate unit tests to Kotest

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/SecureConnectionException.kt, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt
Also catch other IOExceptions
Part 1/2 for #448
=> Add SecureConnectionException for all SSL related exceptions

jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/discovery/RecommendedServerDiscovery.kt
=> Catch all ApiClientException instances in RecommendedServerDiscovery

.github/workflows/sdk-docs.yaml
Looking into publishing the markdown docs too, that's a next PR though.
Fixes #211
=> Build and deploy Dokka documentation in CI

.github/workflows/gradlew-update.yaml, .github/workflows/gradlew-validate.yaml, .github/workflows/merge-conflict-labeler.yaml, .github/workflows/sdk-docs.yaml, .github/workflows/sdk-lint.yaml, .github/workflows/sdk-publish.yaml, .github/workflows/sdk-test.yaml, .github/workflows/sdk-unstable-branch.yaml, .github/workflows/sdk-update-api-spec.yaml
Also fixed a small mistake in the markdown linting
=> Use ubuntu-22.04 in workflows

.github/workflows/gradlew-update.yaml, .github/workflows/gradlew-validate.yaml, .github/workflows/repo-merge-conflict.yaml, .github/workflows/sdk-docs.yaml, .github/workflows/sdk-lint.yaml, .github/workflows/sdk-publish.yaml, .github/workflows/sdk-test.yaml, .github/workflows/sdk-unstable-branch.yaml, .github/workflows/sdk-update-api-spec.yaml
**Changes**
- Use consistent naming scheme
- Use organization check instead of repository check
**Issues**
=> Update GitHub actions workflows

jellyfin-model/api/jellyfin-model.api, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/TranscodingInfo.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/hooks/HooksModule.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/hooks/model/TranscodingInfoTranscodeReasonsHook.kt
This is a temporary fix to avoid crashes. The actual issue **should** be fixed in the server.
Closes #510.
=> Add TranscodingInfoTranscodeReasonsHook to fix issue with OpenAPI spec

openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/CurrentUserIdDefaultValue.kt
Needed to compare two default value instances for an upcoming change in the generator.
=> Make CurrentUserIdDefaultValue a data class

openapi-generator/src/main/kotlin/org/jellyfin/openapi/Main.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/MainModule.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/cli/BaseCommand.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/cli/GenerateCommand.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/cli/MainCommand.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/cli/VerifyCommand.kt
Fixes #623 not working because the dependencies were already injected :-)
=> Use lazy injection for openapi-generator CLI

gradle/libs.versions.toml, jellyfin-core/build.gradle.kts
Also added it to version catalog
=> Bump Android SDK to 33

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/HttpClientOptions.kt, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/sockets/OkHttpWebsocketSession.kt, jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/discovery/RecommendedServerDiscovery.kt
Closes https://github.com/jellyfin/jellyfin-sdk-kotlin/issues/637
Messed up the previous PR, my bad!
@Maxr1998 @nielsvanvelzen
=> refactor: convert Long to Duration for `HttpClientOptions`

.github/workflows/sdk-update-api-spec.yaml
Should fix a regression from #668
=> Fix invalid comitter/author in Update OpenAPI workflow

jellyfin-model/src/commonMain/kotlin/org/jellyfin/sdk/model/socket/SessionsStopMessage.kt
=> Fix wrong serial name for SessionsStopMessage

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/helper/ReconnectHelper.kt
Previously when the WebSocket connection failed it would wait 30 seconds before reconnecting and give after 2.5 minutes. With this change it will gradually increase the delay starting from 600 milliseconds up to every 1.5 minutes over a timespan of about 15 minutes. This results in a nearly-immediate reconnect for recoverable errors (network dip/serialization issue/wrong message) and pretty fast reconnects for server restarts.
=> Use slowly increasing WebSocket reconnect delay

jellyfin-api-ktor/src/jvmMain/kotlin/org/jellyfin/sdk/api/ktor/KtorClient.kt, jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/SecureConnectionException.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/ssl/BadPeerSSLKeyException.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/ssl/HandShakeCertificateException.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/ssl/HandshakeCertificateException.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/ssl/InvalidSSLProtocolImplementationException.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/ssl/PeerNotAuthenticatedException.kt, jellyfin-core/api/android/jellyfin-core.api, jellyfin-core/api/jvm/jellyfin-core.api, jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/discovery/RecommendedServerDiscovery.kt, jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/discovery/RecommendedServerIssue.kt, jellyfin-core/src/jvmTest/kotlin/org/jellyfin/sdk/api/SSLResolverTests.kt
Closes #351 
- Add UnsupportedSSL Issue
- Add ServerUnavailable Issue
=> add unsupported ssl and server unavailable issues

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/ApiClient.kt
Forgot to add this in #796... oops
=> Add ignorePathParameters to ApiClient.createUrl

buildSrc/src/main/kotlin/Publishing.kt
This is a workaround for https://github.com/gradle/gradle/issues/26091
=> Fix failure when signing during publishing

openapi-generator/build.gradle.kts
Fixes the daily spec update CI failing
=> Fix updateApiSpec* tasks not specifying dependency order

samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Discover.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Libraries.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Login.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Observe.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Ping.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Users.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/logging.kt
Use an actual logger instead of println
=> Improve logging in kotlin-cli sample

jellyfin-model/api/jellyfin-model.api, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/BaseItemDto.kt, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/LibraryOptions.kt, openapi.json
=> Update API to 10.9.0-unstable.20240430191733

jellyfin-core/api/android/jellyfin-core.api, jellyfin-core/api/jvm/jellyfin-core.api, jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/discovery/RecommendedServerIssue.kt
- Use data object for RecommendedServerIssue.MissingVersion
=> Use data object for RecommendedServerIssue.MissingVersion

docs/guide/authentication.md, docs/guide/getting-started.md, docs/guide/websockets.md
Update documentation for the upcoming 1.5 release of the SDK. Changes include new function signatures and the new WebSocket implementation.
=> Update documentation for 1.5

jellyfin-model/src/commonMain/kotlin/org/jellyfin/sdk/model/FileInfo.kt
https://github.com/jellyfin/jellyfin-sdk-kotlin/pull/946#discussion_r1623638283
=> Fix typo in FileInfo.mediaType kdoc

jellyfin-api-ktor/api/jellyfin-api-ktor.api, jellyfin-api-ktor/src/jvmMain/kotlin/org/jellyfin/sdk/api/ktor/KtorClient.kt, jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/ApiClient.kt, samples/java-cli/src/main/java/org/jellyfin/sample/cli/Main.java
- Remove deprecated setters from ApiClient
- Make KtorApiClient final (can't be extended)
=> Remove deprecated setters from ApiClient

jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/Jellyfin.kt
Bump the minimum supported API version to 10.10
=> Bump minimumVersion to 10.10

jellyfin-api-ktor/build.gradle.kts, jellyfin-api/build.gradle.kts, jellyfin-core/build.gradle.kts, jellyfin-model/build.gradle.kts
=> Update Gradle configuration for javadoc tasks

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/DefaultSocketApi.kt
I've been debugging WebSocket related issues for the past hour or so and this issue came up when trying to connect while the Jellyfin 10.11 setup server is still online. Unfortunately it does not fix the main issue I was having.
=> Fix edge case causing WebSocket reconnection to stop working

docs/.vitepress/config.ts, docs/migration/v1.5.md, docs/migration/v1.6.md, docs/migration/v1.7.md
Adding docs for versions from a few years ago. Good job me.
Fixes #983
=> Add migration documentation for 1.7 and previous
