android/src/main/java/mediabrowser/apiinteraction/android/AndroidLogger.java
Add an implementation of `ILogger` that uses the Android Log utility. This is to replace the usage of `ConsoleLogger` in the Android TV app which uses `System.out` and therefore is not properly tagged in Android logs.
=> Add Android implementation of ILogger

android/src/main/java/org/jellyfin/apiclient/interaction/VolleyHttpClient.java, android/src/main/java/org/jellyfin/apiclient/interaction/VolleyStringRequest.java, library/src/main/java/org/jellyfin/apiclient/interaction/ApiClient.java, library/src/main/java/org/jellyfin/apiclient/interaction/connectionmanager/ConnectionManager.java, library/src/main/java/org/jellyfin/apiclient/interaction/websocket/ApiWebSocket.java, library/src/main/java/org/jellyfin/apiclient/model/apiclient/ServerCredentials.java, library/src/main/java/org/jellyfin/apiclient/model/dlna/ConditionProcessor.java, library/src/main/java/org/jellyfin/apiclient/model/dlna/DeviceProfile.java, library/src/main/java/org/jellyfin/apiclient/model/dto/BaseItemDto.java, library/src/main/java/org/jellyfin/apiclient/model/entities/MediaStream.java, library/src/main/java/org/jellyfin/apiclient/model/extensions/StringHelper.java
Restores the `null` safe `equalsIgnoreCase` helper and changes the order of some native `equalsIgnoreCase` parameters to avoid `NullPointerException`s.
=> Restore null safe equalsIgnoreCase helper

library/src/main/java/org/jellyfin/apiclient/interaction/BaseApiClient.java, library/src/main/java/org/jellyfin/apiclient/interaction/connectionmanager/ValidateAuthenticationResponse.java
This addresses the issue in https://github.com/jellyfin/jellyfin-androidtv/issues/155 where the initial user lookup uses the old "mediabrowser" api endpoint.
=> Use ApiClient methods for url generation

build.gradle, gradle/wrapper/gradle-wrapper.properties
Required for jellyfin/jellyfin-androidtv#207, as for composite builds the gradle versions have to match.
=> Bump gradle and build tools to parity with Android TV client

library/src/main/java/org/jellyfin/apiclient/model/dto/BaseItemDto.java, library/src/main/java/org/jellyfin/apiclient/model/dto/BaseItemType.java
The Server does not support them anymore, so I am removing the `Game` and `GameGenre` `BaseItemType`s. There's still more game related stuff in the `BaseItemDto`, which could also be deleted, but since this will be deprecated at some point anyway, I don't care enough to do it.
=> Delete Game and GameGenre ItemTypes

library/build.gradle, library/src/main/java/org/jellyfin/apiclient/interaction/websocket/ApiWebSocket.java, library/src/main/java/org/jellyfin/apiclient/interaction/websocket/JavaWebSocketClient.java
Looking at the logs the app showed me it tried to connect but the connection would close within a few sec. I noticed the path was set to `/embysocket` but web connects to `/socket` so I changed that.
It still didn't work... What could happen? Hmm looking at the code I noticed the `onClose` method gets 3 parameters: `int i, String s, boolean b` but they aren't logged.. Let's log them!
The error was in string s and said: `draft org.java_websocket.drafts.Draft_10@236b291 refuses handshake`.. Well.. What's draft 10? It's an old version of the websocket spec! Can we upgrade it? Our library supports setting the draft as parameter in the constructor so I set it to the latest version available, this was 76.. Still didn't work :(
Looking at Wikipedia I saw there's a newer version for the protocol …
=> Update Java-WebSocket to 1.4.0 and some misc fixes

android/build.gradle.kts
Build _might_ fail because of the appcompat library. Next PR will upgrade it to androidx
=> Upgrade Android compile/target version

README.md
Removes inaccurate comment about a tangible software license.
=> Remove reference to tangible in README

android/build.gradle.kts, build.gradle.kts, gradle.properties, library/build.gradle.kts, model/build.gradle.kts
This PR will fix #2 and add support for deployment to Bintray! It's not automated yet, that will be done in a future PR.
**How to use**
Three environment variables should be used:
- `BINTRAY_USER` should be set to the deployment user
- `BINTRAY_KEY` should be set to the deployment key
- `JELLYFIN_VERSION` is optional and will fallback to "SNAPSHOT" but should normally be the same as the git tag
During development I used my own account to deploy to, a sample which deployed this branch as 0.0.1 can be found here: https://bintray.com/nielsvanvelzen/jellyfin-apiclient-java/jellyfin-apiclient-java.
Closes #2
=> Publish to Bintray

library/build.gradle.kts, model/build.gradle.kts
This is a simple one that will be needed for future changes, all modules now support Kotlin. I also fixed a small mistake in the model build.gradle.kts defining the maven plugin a second time
=> Enable Kotlin support for all modules

library/src/main/java/org/jellyfin/apiclient/interaction/BaseApiClient.java, model/src/main/java/org/jellyfin/apiclient/model/querying/ItemsByNameQuery.java
Add support for SearchTerm on by-name API queries.
See [backend](https://github.com/jellyfin/jellyfin/blob/18953d95e6692290bf56547d4c9614790687654c/MediaBrowser.Api/UserLibrary/BaseItemsByNameService.cs#L136).
=> Add support for SearchTerm on ItemByNameQueries

samples/kotlin-console/README.md, samples/kotlin-console/build.gradle.kts, samples/kotlin-console/src/main/kotlin/org/jellyfin/sample/console/Main.kt, samples/kotlin-console/src/main/kotlin/org/jellyfin/sample/console/cli/Discover.kt, samples/kotlin-console/src/main/kotlin/org/jellyfin/sample/console/cli/Libraries.kt, samples/kotlin-console/src/main/kotlin/org/jellyfin/sample/console/cli/Login.kt, samples/kotlin-console/src/main/kotlin/org/jellyfin/sample/console/utils/GarbageHttpClient.kt, samples/kotlin-console/src/main/kotlin/org/jellyfin/sample/console/utils/callApi.kt, samples/kotlin-console/test.sh, settings.gradle.kts
This sample project uses the kotlinx-cli library to build a command line tool that uses the Jellyfin
library. It's used as a showcase of the libraries abilities and is not meant for general use.
Features include:
- Server discovery
- Authenticate
- List libraries
Assuming the binary is called `jellyfin` the following sample will list all libraries in the demo instance:
```sh
jellyfin libraries --server https://demo.jellyfin.org/stable --token $(jellyfin login --server https://demo.jellyfin.org/stable --username demo)
```
This command is also provided in the `test.sh` file. It requires a local install first using `./gradlew installDist`.
---
That was a copy of the README from the sample. This sample is purely meant for testing the library for now. It only contains some really basic …
=> Add kotlin-console example using kotlinx.cli and the library

README.md, build.gradle.kts, library/src/main/java/org/jellyfin/apiclient/discovery/ServerDiscovery.kt, samples/kotlin-console/src/main/kotlin/org/jellyfin/sample/console/Main.kt, samples/kotlin-console/src/main/kotlin/org/jellyfin/sample/console/cli/Libraries.kt, samples/kotlin-console/src/main/kotlin/org/jellyfin/sample/console/cli/Login.kt
Fixed server discovery sometimes emitting the same server multiple times. It will now prevent this by remembering server ids.
Also fixed some miscellaneous issues:
- Removed Azure pipeline badge from README as it didn't work and the status can be seen per commit anyway
- Some grammar, spelling and rephrasing changes in README
- Removed some debug code comments from the CLI sample
- Made CLI sample arguments private
- Updated Gradle plugin version
=> Fix discovery duplicates

azure-pipelines.yml
What this should do:
- Build master and PR's
- Test master and PR's
- Upload .jar files to GitHub releases (including source jars)
- Publish library to [Bintray](https://bintray.com/jellyfin/jellyfin-apiclient-java/jellyfin-apiclient-java)
- Set version of the library based on the git tag
What needs to be done by someone with access to Azure:
- Add 2 environment variables called `BINTRAY_USER` and `BINTRAY_KEY` with credentials for the publisher. We should probably create a bot account for that.
If everything is ready and checked by living humans with more Azure pipeline knowledge than me we could theoretically release 0.7.0.
---
See #54 for the Bintray PR
---
This PR closes #59
=> Rewrite Azure pipeline based on ATV app pipeline

android/build.gradle.kts, build.gradle.kts
This PR will automatically set the Android version name and code based on the "jellyfin.version" property. This means that based on #78 when releasing the git tag is the version used for the build. No need to commit a version change anymore.
=> Generate Android version code

azure-pipelines.yml
To help add Bintray publishing as requested in #54/ #78. 
This is required to have access to the secret variable in the task.
=> Add env variable mapping

.gitignore, android/build.gradle.kts, build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Properties.kt, buildSrc/src/main/kotlin/Publishing.kt, buildSrc/src/main/kotlin/Semver.kt, library/build.gradle.kts, samples/kotlin-console/build.gradle.kts
This will solve some things:
- No need to paste functions inside of build.gradle.kts scripts, making those more readable
- Sharing dependency versions, update them in a single place
- Slightly improved build times (barely noticable)
Not a lot of code was added, it was mostly moving things around. Some new code in `Dependencies.kt` though.
=> Add buildSrc gradle project

azure-pipelines.yml
I did some testing and noticed that more .jar files were be picked up (buildSrc.jar). I made the glob more strict to only upload the generated libraries.
I also added distributions to the uploads, this currently includes a build of the console example (called "kotlin-console-$VERSION.zip") that includes all used libraries etc. for easy use.
The globs are made in a way that adding new samples or library modules won't require changes.
=> Fix release assets uploading the wrong files

azure-pipelines.yml, buildSrc/src/main/kotlin/Publishing.kt
Also makes the environment variable for the key uppercase. It shouldn't matter but it looks prettier.
=> Fix incorrect Bintray repository URL

android/build.gradle.kts
This is a requirement for inclusion in JCenter. Other modules already include sources, just Android being different.
=> Add sources to published android module

api/build.gradle.kts, api/src/main/kotlin/org/jellyfin/apiclient/api/client/KtorClient.kt, api/src/main/kotlin/org/jellyfin/apiclient/api/client/MissingPathVariableError.kt, api/src/main/kotlin/org/jellyfin/apiclient/api/client/Response.kt, api/src/main/kotlin/org/jellyfin/apiclient/api/client/adapter/LocalDateTimeTypeAdapter.kt, api/src/main/kotlin/org/jellyfin/apiclient/api/client/adapter/UUIDTypeAdapter.kt, api/src/test/kotlin/org/jellyfin/apiclient/api/client/KtorClientTests.kt, api/src/test/kotlin/org/jellyfin/apiclient/api/client/adapter/UUIDTypeAdapterTests.kt, settings.gradle.kts
Part **3** of multiple
Merge after #92 
The current implementation is minimal and some code is missing (extensions + java compat). API calls use Kotlin delegates to make pretty code. Calling an API will look like this:
```kotlin
fun `authentication test`() = runBlocking {
val userApi = UserApi(...)
val auth: Response<AuthenticationResult> = userApi.authenticateUserByName("demo", "")
val authDelegated: AuthenticationResult by userApi.authenticateUserByName("demo", "")
}
```
=> Add minimal API module with hardcoded Authorization header

api/src/main/kotlin/org/jellyfin/apiclient/api/client/compatibility/JavaCallback.kt, api/src/main/kotlin/org/jellyfin/apiclient/api/client/compatibility/JavaDataCallback.kt
Part **4** of multiple
Merge after #94 
Coroutines in Java aren't really a thing, this PR adds a solution to use the API in Java. Sample:
```java
UserApi instance = new UserApi(createClient());
AuthenticateUserByName data = new AuthenticateUserByName("demo", null, "");
instance.authenticateUserByName(data, new JavaCallback<AuthenticationResult>() {
@Override
public void onResponse(@Nullable Response<AuthenticationResult> response) {
assert response != null;
System.out.println(response.getData());
}
});
```
```java
UserApi instance = new UserApi(createClient());
AuthenticateUserByName data = new AuthenticateUserByName("demo", null, "");
instance.authenticateUserByName(data, new JavaDataCallback<AuthenticationResult>() {
@Override
public void onData(@Nullable AuthenticationResult data) { …
```
=> Add Java compatibility to api module

api/src/main/kotlin/org/jellyfin/apiclient/api/client/extensions/UserApiExtensions.kt
Part **5** of multiple
Merge after #94
Currently just a single extension but the idea is to add more in the future. These extensions help simplifying API usage.
```kotlin
// Before
userApi.authenticateUserByName(AuthenticateUserByName(username = "demo", pw = null, password = "demo"))
// After
userApi.authenticateUserByName(username = "demo", password = "demo")
```
=> Add UserApi.authenticateUserByName extension

android/build.gradle.kts, api/build.gradle.kts, build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, library/build.gradle.kts, model/build.gradle.kts, openapi-generator/build.gradle.kts, samples/kotlin-console/build.gradle.kts
The buildSrc structure wasn't added yet when I started on the OpenAPI branch and updating would be a pain before everything was merged. So here it is!
Fixes the mix of stdlib-jdk7 and stdlib-jdk8.
I did not update the versions, although using Kotlin 1.4 is planned when the new kotlinpoet release is released.
=> Use buildSrc in new modules

api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/AudioApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/ConfigurationApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/DlnaServerApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/DynamicHlsApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/EnvironmentApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/HlsSegmentApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/ImageApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/ImageByNameApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/ItemLookupApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/LibraryApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/LiveTvApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/MediaInfoApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/PluginsApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/RemoteImageApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/SubtitleApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/UniversalAudioApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/VideoAttachmentsApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/VideoHlsApi.kt, api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/VideosApi.kt, api/src/main/kotlin/org/jellyfin/apiclient/api/client/ApiClient.kt, api/src/main/kotlin/org/jellyfin/apiclient/api/client/KtorClient.kt, openapi-generator/README.md, openapi-generator/src/main/kotlin/org/jellyfin/openapi/MainModule.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/ApiBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationUrlBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiReturnTypeBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/hooks/HooksModule.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/hooks/OperationUrlHook.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/hooks/api/BinaryOperationUrlHook.kt
Because we need things like `ImageApi.getItemImageUrl` for Glide etc.
It uses a hook so we can easily change the behavior. The current behavior is to always create url functions for operations that use a GET request and return binary data.
_Like always, I suggest reviewing per commit._
=> Add operation url function to API services

android/proguard-rules.pro
**This PR targets the release branch**
Added an additional rule to the ProGuard configuration to fix jellyfin/jellyfin-android#147.
I'll tag a release after merge
=> Add discovery models to ProGuard rules

build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, jellyfin-api/build.gradle.kts, jellyfin-core/build.gradle.kts, jellyfin-model/build.gradle.kts, jellyfin-platform-android/build.gradle.kts, openapi-generator/build.gradle.kts
Changes:
- Enabled Android core library desugaring
- [Documentation](https://developer.android.com/studio/write/java8-support]
- This is required to use java.time in older Android versions
- Untested at this moment, need to test one of the apps (ATV/android) in an emulator when upgraded
- Upgraded to kotlinx.serialization 1.0.0
- Since the JSON functionality is now it's own library I had to change the dependencies to use the json library
- Removed stdlib dependency since Kotlin 1.4 adds it automagically
=> Enable Android core library desugaring

.ci/azure-pipelines.yml
**Changes**
* updates how the `JELLYFIN_VERSION` gets set (uses now the same mechanism as [jellyfin/jellyfin](https://github.com/jellyfin/jellyfin/blob/2375c35c4a966a469dd97f33deb57b342498b905/.ci/azure-pipelines-package.yml#L119))
* updates GitHubRelease task to select correct tag with new `JELLYFIN_VERSION`
* change to align publish steps more with the ci in jenkins/jenkins-androidtv ([Line 75 and down](https://github.com/jellyfin/jellyfin-androidtv/blob/727a2e8e351ac9a1e18049c7dd303005ecabbff7/.ci/azure-pipelines.yml#L75))
**Issues**
* more #83 
**Relevant Documentation**
* [GitHubRelease task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release)
* > Assets - (Optional) Specify  the files to be uploaded as assets for the release. You can use wildcard …
=> update(ci): change ci publish steps ... again

android/src/main/kotlin/org/jellyfin/apiclient/interaction/AndroidDevice.kt
Includes a part of the fix in #136 to at least fix the crashes in the Android app for devices with corrupted names.
=> Normalize the Android device name (backport)

jellyfin-platform-android/build.gradle.kts, jellyfin-platform-android/src/main/kotlin/org/jellyfin/apiclient/interaction/AndroidDevice.kt, jellyfin-platform-android/src/test/kotlin/org/jellyfin/apiclient/interaction/AndroidDeviceTests.kt
Fixes some issues we have in the Android app with corrupt device names. See my other PR for a backport. The comment on the [normalize] function explains the changes.
=> Normalize the Android device name

jellyfin-api/build.gradle.kts, jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/ApiClient.kt, jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/KtorClient.kt, jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/MissingPathVariableError.kt, jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/Response.kt, jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/compatibility/JavaCallback.kt, jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/compatibility/JavaDataCallback.kt, jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/extensions/UserApiExtensions.kt, jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/sockets/SocketSubscription.kt, jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/sockets/WebSocketApi.kt
Enables explicit API mode in the jellyfin-api module. Also added some really small naming/comment/error message fixes.
Part of #130
=> Enable explicit API mode in jellyfin-api

openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiReturnTypeBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/constants/MimeType.kt
@crobibero fixed a bunch of warnings and introduced a new mime for fonts "font/*" in jellyfin/jellyfin#4486.
This PR adds support for fonts by converting them to a binary stream. OpenAPI spec update later.
=> Support font files as binary content in OpenAPI generator

jellyfin-platform-android/build.gradle.kts, jellyfin-platform-android/src/main/kotlin/org/jellyfin/apiclient/JellyfinAndroid.kt, jellyfin-platform-android/src/main/kotlin/org/jellyfin/apiclient/discovery/AndroidBroadcastAddressesProvider.kt, jellyfin-platform-android/src/main/kotlin/org/jellyfin/apiclient/interaction/AndroidDevice.kt
Enables explicit API mode in the jellyfin-platform-android module. Had to use a workaround to enable it because the explicitApi() DSL is not supported for Android modules. https://youtrack.jetbrains.com/issue/KT-37652
Part of #130
=> Enable explicit API mode in jellyfin-platform-android

jellyfin-core/build.gradle.kts, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/Jellyfin.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/JellyfinOptions.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/AddressCandidateHelper.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/DiscoveryBroadcastAddressesProvider.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/DiscoveryService.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/JavaNetBroadcastAddressesProvider.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/LocalServerDiscovery.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/RecommendedServerDiscovery.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/RecommendedServerInfo.kt, jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/RecommendedServerInfoScore.kt, jellyfin-core/src/test/kotlin/org/jellyfin/apiclient/discovery/DiscoveryServiceTests.kt, jellyfin-core/src/test/kotlin/org/jellyfin/apiclient/discovery/MockDiscoveryBroadcastAddressesProvider.kt
Enables explicit API mode in the jellyfin-core module. Also fixes a few linter issues and made the JavaNetBroadcastAddressesProvider use the IO coroutine dispatcher.
Part of #130
=> Enable explicit API mode in jellyfin-core

openapi-generator/README.md, openapi-generator/build.gradle.kts
Uses repo.jellyfin.org to retrieve stable/unstable specs
- `downloadApiSpecStable` - downloads https://repo.jellyfin.org/releases/openapi/jellyfin-openapi-stable.json
- `downloadApiSpecUnstable` - downloads https://repo.jellyfin.org/releases/openapi/jellyfin-openapi-unstable.json
- `updateApiSpecStable` - runs `downloadApiSpecStable` and then `generateSources`
- `updateApiSpecUnstable` - runs `downloadApiSpecUnstable` and then `generateSources`
_Maybe I should add a task to automatically make commits too_
=> Add download and update tasks for OpenAPI spec

jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/KtorClient.kt, jellyfin-api/src/test/kotlin/org/jellyfin/apiclient/api/client/KtorClientTests.kt, jellyfin-model/src/test/kotlin/org/jellyfin/apiclient/model/discovery/ServerVersionTests.kt, jellyfin-model/src/test/kotlin/org/jellyfin/apiclient/model/serializer/UUIDSerializerTests.kt
- Support `null` as value for a path parameter
- According to server devs we need to remove it from the path
- Added one additional test for nullable parameters
- Updated all tests to use public visibility - otherwise the IDE will complain because of strictApiMode
- Formatted some tests to make Detekt happy
=> Support nullable parameters in path

jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/AudioApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/ConfigurationApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/DlnaServerApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/DynamicHlsApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/HlsSegmentApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/ImageApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/ImageByNameApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/ItemLookupApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/LibraryApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/LiveTvApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/MediaInfoApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/RemoteImageApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/SubtitleApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/UniversalAudioApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/VideoAttachmentsApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/VideoHlsApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/VideosApi.kt, jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/ApiClient.kt, jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/KtorClient.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationUrlBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/constants/Strings.kt
This will help when we request a URL for an image to load it with Glide but the image endpoint is authenticated.
As always: first commit is the actual change, the second updates the generated code.
=> Add option to generate URLs with access token added

jellyfin-core/build.gradle.kts
To use the ByteReadChannel there's a lot of extension functions. Unfortunately those weren't exposed and I couldn't `.copyTo(outputStream)` making it quite useless.
Exposing the ktor-http package fixes this.
https://api.ktor.io/1.4.0/io.ktor.utils.io/-byte-read-channel/index.html
=> Expose ktor-http library

.editorconfig, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationUrlBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiApiServicesBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/constants/Security.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/ApiServiceOperation.kt
OpenAPI spec from server now includes security metadata for all operations so we can determine the default value for this parameter now. Tested it with the latest openapi spec and it worked as expected.
Will update the spec (again) later when 10.7.0-rc.1 is released.
=> Set default value for requireAuthentication

jellyfin-api/src/main/kotlin/org/jellyfin/apiclient/api/client/KtorClient.kt
Escape pretty much all characters to be safe.
References:
https://github.com/jellyfin/jellyfin/blob/79578521b8083588638ecdf70262346055b4db41/Emby.Server.Implementations/HttpServer/Security/AuthorizationContext.cs#L243-L284
https://github.com/jellyfin/jellyfin/blob/79578521b8083588638ecdf70262346055b4db41/Emby.Server.Implementations/HttpServer/Security/AuthorizationContext.cs#L286-L290
=> Encode device name in authorization header

jellyfin-core/src/main/kotlin/org/jellyfin/apiclient/discovery/LocalServerDiscovery.kt
Found this while I tried debugging an issue on the 0.7 branch. We don't read the value of EndpointAddress but the serializer really wanted to read it.
=> Fix server discovery not ignoring unknown keys

jellyfin-model/src/main/kotlin/org/jellyfin/apiclient/model/serializer/UUIDSerializer.kt, jellyfin-model/src/test/kotlin/org/jellyfin/apiclient/model/serializer/UUIDSerializerTests.kt
- Fixed the regex (apparently we stopped using UUIDv4 at some point after 10.7RC1)
- Simplified deserialize function
- Added 2 additional test strings
=> Fix uuid parser sometimes failing

jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/MediaInfoApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/PlaylistsApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/TvShowsApi.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/ApiBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationUrlBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/constants/Strings.kt, openapi.json
- Change behavior for deprecated parameters in API operations to generate a secondary function
The @deprecated annotation is not supported by Kotlin (although IntelliJ worked fine with it!). The new behavior will generate one function with the deprecated members removed and another one with them added. The latter will have a "Deprecated" suffix in the name and a @deprecated annotation on the function.
- Update OpenAPI specification to 10.7~RC3
The changes between RC2-RC3 are small so you can see the new behavior perfectly fine. I didn't notice that the old approach didn't work because this is the first release that adds deprecated parameters.
=> Update OpenAPI specification to 10.7~RC3

jellyfin-model/src/main/kotlin/org/jellyfin/apiclient/model/serializer/UUIDSerializer.kt
jellyfin-android needs to parse UUID's passed from the webclient. The `UUID.parseString` function in Java only allows hyphenated strings so we need to expose the apiclient UUID parser to parse the simple notation.
This PR adds two new extension functions to the String class to parse UUID's. The serializer now uses those functions to prevent duplicate code.
=> Add String.toUUID and String.toUUIDOrNull functions

build.gradle.kts, library/src/main/java/org/jellyfin/apiclient/interaction/BaseApiClient.java
Needed for authentication rewrite in jellyfin-androidtv. Note that `SetAuthenticationInfo` should be called after to reset the HTTP header values.
=> Add setDevice method

.github/workflows/gradlew-update.yaml, .github/workflows/gradlew-validate.yaml, .github/workflows/merge-conflict-labeler.yaml
Part of this comes from #163 with some slight improvements, the labeler comes from the ATV repo with some changes (added a schedule).
=> Add merge conflict labeler and gradle update and validate tasks

.github/workflows/gradlew-update.yaml, .github/workflows/gradlew-validate.yaml
Apparently two workflows with the same name is confusing
=> Rename gradle wrapper workflows

jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/AudioApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/DynamicHlsApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/MediaInfoApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/UniversalAudioApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/VideoHlsApi.kt, jellyfin-api/src/main/kotlin-generated/org/jellyfin/apiclient/api/operations/VideosApi.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationUrlBuilder.kt
Fixes a different implementation for the buildParameter function.
The Url functions now support default values too :)
=> Use OperationBuilder as parent class in OperationUrlBuilder and remove duplicate code

.ci/azure-pipelines.yml, .github/workflows/apiclient-test.yaml
- Add new workflow "apiclient-test"
- this runs the test task which will build and test all modules
- Remove test and build jobs from azure
- Also changed the triggers to only run on tags now so the azure file is correct
- 1.0.0 will not use azure for publishing though
The CI file is largely copied from #163 but with changes in the caching keys
=> Move build and testing CI to GitHub Actions

.ci/azure-pipelines.yml, .github/workflows/apiclient-publish.yaml, build.gradle.kts, buildSrc/src/main/kotlin/Pom.kt, buildSrc/src/main/kotlin/Properties.kt
This PR adds the publish CI to GitHub Actions. It triggers for both tags and the master branch. The master branch will release "latest-SNAPSHOT" builds, tags release a build based on the git tag. It also updates the Azure CI to only publish the GitHub releases, my next PR will move that to GitHub too.
Additional changes:
- Update POM (src: https://central.sonatype.org/pages/requirements.html)
- Use getProperty util function so we can pass properties via environment variables
- Add logging to getProperty function, useful for debugging (shown with `--info` parameter when invoking Gradle)
- Default to emtpy string when signing password is null
=> Move publishing CI to GitHub actions

.github/workflows/gradlew-update.yaml, .github/workflows/merge-conflict-labeler.yaml, .github/workflows/sdk-publish.yaml, .github/workflows/sdk-test.yaml, buildSrc/src/main/kotlin/Pom.kt
Depends on #196 and #193. This renames the GitHub workflows and pom configuration.
Merge **after** renaming the repository.
=> Rename apiclient to SDK (after repository rename)

README.md
=> Update README for 1.0.0 version

jellyfin-platform-android/build.gradle.kts
The Android publication is created after evaluation because it depends on some things generated by the android plugin. The `defaultPom()` that is added in the main build file is therefor not added.
Fixed it by adding it manually to the Android module.
Tested by running `gradlew publishToMavenLocal` and verifying the generated files.
Partial fix for https://github.com/jellyfin/jellyfin-sdk-kotlin/issues/176#issuecomment-805068411
=> Fix missing pom in android module

build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, gradle.properties, jellyfin-api/build.gradle.kts, jellyfin-core/build.gradle.kts, jellyfin-model/build.gradle.kts, jellyfin-platform-android/build.gradle.kts
The Dokka plugin will generate javadoc files and those are added to the publications. Unfortunately Dokka loves memory so I had to increase it in the gradle.properties.
Partial fix for https://github.com/jellyfin/jellyfin-sdk-kotlin/issues/176#issuecomment-805068411
=> Publish javadoc using Dokka

README.md
I'd just like to interject for a moment. What you're referring to as Jellyfish, is in fact, Jellyfin, or as I've recently taken to calling it, Emby plus Jellyfin. Jellyfin is not a media server unto itself, but a free component of a media server as defined by Luke Pulverenti. Through a peculiar turn of events, the version of Jellyfin which is widely used today is basically developed with slave labor. Please recognize the harm caused to the slaves by misnaming the project.
---
The .svg extension doesn't really matter but added it so it's the same as the shield on top of the README.
=> Fix broken badge in README

.github/workflows/sdk-publish.yaml
This PR adds the `closeAndReleaseSonatypeStagingRepository` task to the publishing script. This wil automatically close&release the staging repository so releases will be 100% automatic. I didn't add it previously so I could verify the staging repository for the validation process.
I'm not sure what happens if we call the task from snapshot builds as the documentation is not clear about it. I'll assume it just works and otherwise make another PR.
Closes #176
=> Automatically release on Sonatype

build.gradle.kts
This fixes an issue with the `dokkaHtmlMultiModule` task not being able to resolve it's dependencies.
=> Add default repositories to all projects

.gitattributes, .github/workflows/sdk-test.yaml, build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, jellyfin-api/api/jellyfin-api.api, jellyfin-core/api/jellyfin-core.api, jellyfin-model/api/jellyfin-model.api, jellyfin-platform-android/api/jellyfin-platform-android.api
This PR adds the binary compatibility validator plugin to validate the exposed API with the last known in the repository. This can be used to automatically detect breaking changes.
The CI will run the `apiCheck` task and report any changes, this forces the contributor to update the API files using the `apiDump` task. This will create a git diff that shows the changes API to the maintainers, we can then chose to accept the API change or request changes.
Errors look like this:
```txt
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':jellyfin-api:apiCheck'.
> API check failed for project jellyfin-api.
--- .....\jellyfin-sdk-kotlin\jellyfin-api\api\jellyfin-api.api
+++ .....\jellyfin-sdk-kotlin\jellyfin-api\build\api\jellyfin-api.api
@@ -66,6 +66,7 @@ …
```
=> Add binary compatibility validation

.github/dependabot.yml, .github/workflows/sdk-publish.yaml, .github/workflows/sdk-test.yaml
This PR aims to update the used GitHub Actions in the CI workflows and provides a dependabot config to keep them up-to-date in the future. (this includes the `actions/setup-java` v2 update and sets it to use `adopt`)
* various GitHub actions version bumps
* dependabot config to check for action updates on a weekly basis
* n/a
You might want to add the Labels `ci` and `github-actions` similar to the [android repo](https://github.com/jellyfin/jellyfin-android/pull/336#issuecomment-815265645), since dependabot is odd and only wants to auto create its own default labels :sweat_smile:
=> ci(deps): update used actions

build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, gradle/libs.versions.toml, jellyfin-api/build.gradle.kts, jellyfin-core/build.gradle.kts, jellyfin-model/build.gradle.kts, jellyfin-platform-android/build.gradle.kts, openapi-generator/build.gradle.kts, samples/kotlin-cli/build.gradle.kts, settings.gradle.kts
Also removed kotlin-stdlib dependency for the two projects still using it.
Plugins and buildscript dependencies cannot use the dependency catalog right now, I'm not sure if that is intended. I kept the old method for that (using buildSrc).
=> Use experimental centralized dependency versions and type-safe project dependencies

.github/workflows/sdk-update-api-spec.yaml
This PR adds a GH Action workflow to run a weekly API gen (via `updateApiSpecStable`) and open a PR if changes are detected. 
* add workflow to check for generated jellyfin API changes
* closes #210 
if you want to the PR to be opened by jellyfin-bot I think you can, but we woul have to change to token used in the `technote-space/create-pr-action` action
=> Add GitHub workflow to automatically update OpenAPI spec and generated sources

.github/dependabot.yml
I should have added it to begin with :facepalm:
=> add missed dependencies label for dependabot PRs

.github/dependabot.yml, .github/workflows/gradlew-update.yaml, .github/workflows/merge-conflict-labeler.yaml, .github/workflows/sdk-publish.yaml
- Use the Jellyfin Bot for all tasks using GitHub tokens
- Use default commit message for Dependabot
=>  Use the Jellyfin Bot for all tasks using GitHub tokens

.github/workflows/sdk-lint.yaml, build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt
Adds linting using Detekt with SARIF files.
Part of #220
=> Add linting in CI using Detekt with SARIF output

.editorconfig, detekt.yml, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/sockets/WebSocketApi.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/JellyfinOptions.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/AddressCandidateHelper.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/LocalServerDiscovery.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/RecommendedServerDiscovery.kt, jellyfin-model/src/main/kotlin/org/jellyfin/sdk/model/ServerVersion.kt, jellyfin-model/src/main/kotlin/org/jellyfin/sdk/model/serializer/UUIDSerializer.kt, jellyfin-platform-android/src/main/kotlin/org/jellyfin/sdk/discovery/AndroidBroadcastAddressesProvider.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/Arguments.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/OpenApiGeneratorError.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationUrlBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/model/EnumModelBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/model/ModelBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/model/ObjectModelBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiApiServicesBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiModelBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiReturnTypeBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiTypeBuilder.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/Options.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Ping.kt
Mostly formatting/style changes.
=> Fix, suppress or modify all Detekt linter issues

jellyfin-core/api/jellyfin-core.api, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/Jellyfin.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/RecommendedServerDiscovery.kt
The recommended version should always be the latest server version (which is stored in apiVersion). The minimumVersion should be the latest server version without significant API changes and is manually updated.
Also added an additional check to the server discovery score system. Non-jellyfin servers now return a BAD score for obvious reasons.
=> Rename recommendedVersion to minimumVersion

jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt, jellyfin-api/src/test/kotlin/org/jellyfin/sdk/api/client/KtorClientTests.kt
Previously, path variables were only replaced properly if they were enclosed within slashes.
Cases like e.g. `/{one}.{two}/` caused a missing path variable error for `one}.{two`.
This commit fixes those cases by iterating over the path manually,
detecting variable start/end manually, while still replacing duplicate slashes.
=> Fix path variable replacement

.github/workflows/sdk-lint.yaml, buildSrc/src/main/kotlin/Dependencies.kt, jellyfin-platform-android/build.gradle.kts
- Update Android Gradle plugin to 4.2
- Add Android linter to linting workflow
Some notes: 4.2 compiles to Java 8 by default so we can remove those settings, SARIF output is disabled by default so it should be enabled. The `lint` task does not run `detekt` by default.
=> Update Android Gradle plugin to 4.2

buildSrc/src/main/kotlin/Dependencies.kt, jellyfin-model/api/jellyfin-model.api, jellyfin-platform-android/build.gradle.kts, openapi-generator/build.gradle.kts, samples/kotlin-cli/build.gradle.kts
- Update Kotlin to version 1.5.0
- Updated mainClassName (deprecated) to new syntax
- Update .api file for jellyfin-model - changed due too kotlinx.serialization thingies in 1.5
JVM target is now 1.8 by default
=> Update Kotlin to version 1.5.0

buildSrc/src/main/kotlin/Dependencies.kt
- Update Dokka to version 1.4.32
Updates the kotlinx.html dep so it won't fail.
https://github.com/Kotlin/dokka/releases/tag/v1.4.32
=> Update Dokka to version 1.4.32

.github/workflows/sdk-unstable-branch.yaml
This new workflow will run for each change in the master branch for when the generator or other code changes and on a daily schedule to make sure the spec is up-to-date.
It will always start out with the code on the master branch and then regenerate the spec with the unstable version and force pushing it. This way the branch is always exactly one commit ahead. It can then be easily compared to see what kinds of magic is added to the API for the next release. It also helps find issues in the spec that need changes in the server or generator.
Example after I ran it on my fork: https://github.com/jellyfin/jellyfin-sdk-kotlin/compare/master...nielsvanvelzen:openapi-unstable
=> Add workflow to maintain an openapi-unstable branch

jellyfin-core/api/jellyfin-core.api, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/AddressCandidateHelper.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/DiscoveryService.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/RecommendedServerDiscovery.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/RecommendedServerInfo.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/RecommendedServerInfoScore.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Discover.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Ping.kt
- Drop baseurl addition - too small of a user base to do this for. Each candidate adds to the amount of HTTP requests to make.
- Always prioritize candidates
- Add new score type: GREAT
- Document all score types to summarize what they mean
- Remove `includeAppendedServers`: too complex, not worth the amount of additional requests
- Completely rewritten the scoring system. Doesn't use points anymore but strict rules instead.
- Easier to maintain and see how it works
- Checks if the server actually responded now
- Uses the new GREAT type if all checks succeed
- Moved some code around, tweaked some calls
- Change the kdoc to reference the used functions instead 
- To prevent outdated comments
- Remove `includeAppendedServers`
- Remove `getRecommendedServer`. Client should determine on it's …
=> Refactor discovery code with better rules

.github/workflows/sdk-unstable-branch.yaml
- Removed "cancel in progress" from concurrency because a cancelled action shows as "failed" in the UI. Now it just waits before executing the next.
- Replaced the `EndBug/add-and-commit@v7.2.0` action with more simple git commands:
- First set the author config (I tried `--author` on the commit but it wouldn't work so I just used git config)
- Create or reset the unstable branch using `git checkout`
- Add all fiels using `git add.`
- Create commit, allowing empty commits for when there are no changes
- Push to openapi-unstable branch, overwriting existing commits
Closes #248
=> Replace commit action with git commands in unstable branch workflow

.github/workflows/gradlew-update.yaml, .github/workflows/merge-conflict-labeler.yaml, .github/workflows/sdk-publish.yaml, .github/workflows/sdk-unstable-branch.yaml, .github/workflows/sdk-update-api-spec.yaml
``GH_TOKEN`` seems to be used internally by GitHub and it's making some actions we're using in some repos fail ([Source](https://github.com/alex-page/github-project-automation-plus/issues/39))
*(PRs made from users of the org are always successful, but PRs that aren't don't work, like Dependabot PRs. This can be checked by looking at the history of server repos and Jellyfin Vue)*
The org-wide secret should be renamed to something else to avoid confusion and further replacements or messes in GH's side. This PR replaces ``GH_TOKEN`` with ``JF_BOT_TOKEN``, which should be pretty generic.
=> Replace GH_TOKEN with JF_BOT_TOKEN

jellyfin-model/api/jellyfin-model.api, jellyfin-model/src/main/kotlin/org/jellyfin/sdk/model/extensions/PairExtensions.kt
`Pair` -> `Model` & `Model` -> `Pair` for:
- NameIdPair
- NameGuidPair
- NameValuePair
- XmlAttribute
=> Add pair extensions to easily convert SDK pairs to and from Kotlin pairs

gradle/libs.versions.toml, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/sockets/WebSocketApi.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/LocalServerDiscovery.kt
I'm probably rewriting the WebSocketApi at some point, I'm not satisfied with the current implementation. The current changes are minimal just to fix the warnings after the update.
=> Update kotlinx.coroutines and fix warnings in WebSocketApi

jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt
Fixes jellyfin/jellyfin-android#368.
=> Catch all types of timeouts and rethrow as ApiClientException

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/extensions/MediaInfoApiExtensions.kt, jellyfin-model/api/jellyfin-model.api, jellyfin-model/src/main/kotlin/org/jellyfin/sdk/model/BitrateMeasurement.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/Main.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Bitrate.kt
Adds 2 new functions to the `MediaInfoApi` class:
- measureBitrate
- detectBitrate
Both return a `BitrateMeasurement` containing requested bytes, response duration and calculated bitrate.
The detect function should normally take between 0.5-3 seconds but can take longer depending on network conditions.
Additionally adds a new bitrate command to the CLI because why not.
=> Add bitrate measurement functions

.github/workflows/sdk-publish.yaml, README.md, build.gradle.kts, buildSrc/src/main/kotlin/Properties.kt
- Add jellyfin.branch property to create versions from a branch name
- Publish openapi-unstable branch as openapi-unstable-SNAPSHOT
- getProperty log set to debug
- Rename `latest-SNAPSHOT` to `master-SNAPSHOT`
- latest is now a fallback which is not used in CI, update your projects using the snapshots to use `master-SNAPSHOT`!
This PR is untested since I can't test this on my fork.
=> Publish openapi-unstable branch as openapi-unstable-SNAPSHOT

jellyfin-core/api/jellyfin-core.api, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/Jellyfin.kt
2 changes:
- Add additional constructor so you can pass the `JellyfinOptions.Builder` to the constructor (no need to call `.build()`)
- Add `@JvmOverloads` to the `createApi` function so you can call `jellyfin.createApi("baseurl")` instead of `jellyfin.createApi("baseurl", null, null, null, null)`
=> Improve usage of Jellyfin class in Java code

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, gradle.properties, samples/kotlin-console/build.gradle.kts
This is the final change for the legacy apiclient. With these changes JitPack should be able to build the release and the apiclient doesn't need JCenter dependencies. **It is highly advised to upgrade to the new SDK, this release is not supported.**
- Disabled Detekt
- Disabled publishing to JCenter
- Removed JCenter repository
- Added MavenCentral repository
- Increased memory for Gradle builds (prevents out of memory)
- Updated Volley to 1.2.0 (1.1.x not available on MavenCentral)
- Downgrade Android build tools to 4.0.x because 4.1 doesn't support the Gradle version
=> Bare minimum changes to allow JitPack build of final apiclient version without JCenter dependencies.

openapi-generator/src/main/kotlin/org/jellyfin/openapi/Generator.kt
This was the easiest way to fix it, although not the prettiest.
=> Fix bad line endings used in openapi generator

openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/extra/DescriptionBuilder.kt
Fixes some comments on the unstable branch.
Original (source):
```
as well as which <see cref="TranscodingProfiles">containers/codecs to transcode to</see> in case it isn't.
```
Original (openapi):
```
as well as which <see cref="P:MediaBrowser.Model.Dlna.DeviceProfile.TranscodingProfiles">containers/codecs to transcode to</see> in case it isn't.
```
Before PR:
```
as well as which `P:MediaBrowser.Model.Dlna.DeviceProfile.TranscodingProfiles`containers/codecs to transcode to</see> in case it isn't.
```
After PR:
```
as well as which containers/codecs to transcode to (`P:MediaBrowser.Model.Dlna.DeviceProfile.TranscodingProfiles`) in case it isn't.
```
=> Fix non self closing <see> and <seealso> elements in descriptions

jellyfin-model/api/jellyfin-model.api, jellyfin-model/src/main/kotlin/org/jellyfin/sdk/model/serializer/LocalDateTimeSerializer.kt, jellyfin-model/src/test/kotlin/org/jellyfin/sdk/model/serializer/LocalDateTimeSerializerTests.kt
Should fix #285 although not directly tested with the api operation mentioned in the issue.
=> Fix formatting of LocalDateTimeSerializer encoding and add tests

openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiApiServicesBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/ApiServiceOperationParameter.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/IntRangeValidation.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/ParameterValidation.kt
Allows for client-side checking of values based on the metadata available in the OpenAPI specification. Right now (with 10.7.x) none of the parameters add any validation metadata.
Sample of generated code with the changes from https://github.com/jellyfin/jellyfin/pull/6276
```kotlin
/**
* Tests the network with a request with the size of the bitrate.
*
* @param size The bitrate. Defaults to 102400.
*/
public suspend fun getBitrateTestBytes(size: Int? = 102400): Response<ByteReadChannel> {
val pathParameters = emptyMap<String, Any?>()
val queryParameters = mutableMapOf<String, Any?>()
require(size in 0..100000000) { "Parameter \"size\" must be in range 0..100000000 (inclusive)." }
queryParameters["size"] = size
val data = null
val response = …
```
=> Add ParameterValidation framework with initial IntRangeValidation

jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/util/AuthorizationHeaderBuilder.kt, jellyfin-api/src/test/kotlin/org/jellyfin/sdk/api/client/AuthorizationHeaderBuilderTests.kt
The regex probably adapted to the system language, allowing incorrect characters. This fixes the issue (tested by one of our users).
Replaces/fixes #295
=> Fix authorization header encoding sometimes not working

jellyfin-core/api/jellyfin-core.api, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/RecommendedServerDiscovery.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/RecommendedServerInfo.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/RecommendedServerIssue.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Discover.kt
This change adds more information to the output of RecommendedServerDiscovery that can help a user debug why they can't connect to their server. The scoring is still the same but now includes a list of issues, in case of `NoSystemInfo` the exception thrown when trying to GET the public server info is added. This one can be an ApiClientException or another Throwable.
Example output of the Kotlin CLI (command `discover https://demo.jellyfin.org/stable`, names of issues renamed after this output was added to the PR)
```
Starting discovery for https://demo.jellyfin.org/stable
Found 3 candidates
https://demo.jellyfin.org/stable: GREAT (replied in 707ms, system information found)
https://demo.jellyfin.org:8096/stable: BAD (replied in 5012ms, system information not found) …
```
=> Emit issue information in RecommendedServerDiscovery

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/sockets/SocketSubscription.kt, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/sockets/WebSocketApi.kt, jellyfin-model/src/main/kotlin/org/jellyfin/sdk/model/socket/IncomingSocketMessage.kt, jellyfin-model/src/main/kotlin/org/jellyfin/sdk/model/socket/OutgoingSocketMessage.kt, jellyfin-model/src/main/kotlin/org/jellyfin/sdk/model/socket/SocketMessage.kt
- Use sealed interfaces for SocketMessage models
- Remove asynchronous signature from WebSocketApi 
- Use httpClientOptions
=> WebSocketApi fixes

gradle/libs.versions.toml, jellyfin-api/build.gradle.kts, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt, jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/sockets/WebSocketApi.kt, jellyfin-core/build.gradle.kts, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/AddressCandidateHelper.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/LocalServerDiscovery.kt, jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/RecommendedServerDiscovery.kt
Kotlin-logging still uses slf4j under the hood so nothing changes for our apps, just add sl4fj-simple as dependency to see the logs from the SDK like always.
=> Replace slf4j with kotlin-logging

gradle/libs.versions.toml, jellyfin-api/build.gradle.kts, jellyfin-model/build.gradle.kts
- Use dokkaHtml instead of dokkaJavadoc for published documentation 
- Only for MPP projects - others still use javadoc!
- This fixes an issue where dokkaJavadoc didn't work and provides multiplatform information in the documentation
- Update Dokka to 1.5.0
Requires #306
=> Use dokkaHtml instead of dokkaJavadoc for published documentation 

.github/workflows/sdk-test.yaml, openapi-generator/README.md, openapi-generator/build.gradle.kts, openapi-generator/src/main/kotlin/org/jellyfin/openapi/Generator.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/Main.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/Verification.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiApiServicesBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/GeneratorResult.kt
This change adds a new CLI flag to the openapi-generator: "`--verify". When set the generator will not write any files but verify if the existing files are valid. This way we can be sure that a pull request updating lots of generated files is valid and doesn't contain malicious changes.
A new Gradle task is added to run the verify function "verifySources" which is executed as part of the sdk-test workflow.
Additionally, logging in the generator now uses kotlin-logging.
A few samples of possible output:
- File content is different
```
[main] ERROR org.jellyfin.openapi.Verification - org\jellyfin\sdk\model\api\BaseItemDto.kt: modified (128c62b24360ed5a6202dd06f711a2f5 -> 84f916d01872e1f64451c132f096a399).
```
- File does not exist in repo - does in spec
```
[main] ERROR …
```
=> Add verify function to openapi-generator

.github/workflows/sdk-lint.yaml, .github/workflows/sdk-publish.yaml, .github/workflows/sdk-test.yaml, .github/workflows/sdk-unstable-branch.yaml, .github/workflows/sdk-update-api-spec.yaml
See https://github.blog/changelog/2021-08-30-github-actions-setup-java-now-supports-dependency-caching/
Results in smaller workflow files etc.
=> Use actions/setup-java caching

jellyfin-core/src/androidMain/kotlin/org/jellyfin/sdk/JellyfinOptions.kt, jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/Jellyfin.kt, jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/JellyfinOptions.kt, jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/util/ApiClientFactory.kt, jellyfin-core/src/jvmMain/kotlin/org/jellyfin/sdk/JellyfinOptions.kt
Add a new option to change the to-be-used ApiClient implementation. This isn't that useful right now as the HTTP method extension functions (get,post,delete) cast the interface to KtorClient. This is something I hope to fix in an upcoming PR.
Part of #207
=> Add ApiClientFactory option to allow different http clients

gradle/libs.versions.toml, jellyfin-api/api/jellyfin-api.api, jellyfin-api/build.gradle.kts, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/ApiClient.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/HttpMethod.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/RawResponse.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/Response.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/extensions/HttpMethodExtensions.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/util/ApiSerializer.kt, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/sockets/WebSocketApi.kt
- Add new class "RawResponse"
- ApiClient is now expected to return an instance of RawResponse
- Uses the new ApiSerializer to read response from RawResponse
- Added ApiClient.request to ApiClient interface
- no longer inline because of the RawResponse class
- Removed (de)serialization responsibility from Ktor(Client)
- Made the HttpClient in KtorClient private
- Use new ApiSerialization in WebSocketApi
Tested with a private app that authenticates (post body), retrieves library items (response body) and downloads (response body bytestream reading) and it worked without any issues.
This PR closes #207 - It doesn't make KtorClient private but allows custom ApiClient instances now. In the future I'd like to move the KtorClient to a separate Gradle module so it can be omitted for advanced …
=> Separate content (de)serialization from ApiClient

docs/migration/v1.1.md
Exactly what the title says. This PR adds a document explaining the migration from 1.0 -> 1.1.
I added a new directory called "docs". Eventually this should be published somewhere so we can add more documentation like install instructions, sample usages, tips & tricks etc.
=> Add v1.1 migration documentation

.github/workflows/sdk-lint.yaml, .github/workflows/sdk-publish.yaml, .github/workflows/sdk-test.yaml, .github/workflows/sdk-unstable-branch.yaml, .github/workflows/sdk-update-api-spec.yaml, gradle.properties
- The AdoptOpenJDK project stopped and migrating to Adoptium is recommended: 
https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/
- Matrix builds (tests) now use Java 11 and 17 instead of 11 and 16.
=> Use Java 17 as default and move to Adoptium distribution

build.gradle.kts, gradle/libs.versions.toml, jellyfin-core/api/android/jellyfin-core.api, jellyfin-core/api/jvm/jellyfin-core.api
This update supports multiple source sets, the old one is now moved to a subdir and updated.
=> Update binary-compatibility-validator to 0.8.0-RC and re-enable jellyfin-core api validation again

jellyfin-model/api/jellyfin-model.api, jellyfin-model/src/commonMain/kotlin/org/jellyfin/sdk/model/extensions/GeneralCommandMessageExtensions.kt, jellyfin-model/src/jvmTest/kotlin/org/jellyfin/sdk/model/extensions/GeneralCommandMessageExtensionTests.kt
GeneralCommandType is the most often used WebSocket message from the server but it's actual informative content (callled arguments) is just a map<string,string>. There is no schema for it (not even in the server!).
To make it easier to read information I added some (operator) extension functions that are case insensitive to allow reading the command messages.
The tests use a valid DISPLAY_MESSAGE command.
--
This is one of multiple pull requests that will rewrite the WebSocket API to make it easier to work with.
=> Add extensions to read arguments from GeneralCommandMessage

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/RawResponse.kt, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt
Fixes a bug in #322 where deserialization exceptions would not be caught anymore.
- KtorClient serializes post bodies but doesn't deserialize responses
- RawResponse deserializes responses
Both of the above are used when calling API functions, previously (before 322) the KtorClient would catch response deserialization issues.
_Considering a 1.1.2 release for this change._
=> Fix SerializationException not catched in RawResponse

jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/DisplayPreferencesDto.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/hooks/HooksModule.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/hooks/model/DisplayPreferencesDtoNullabilityFixHook.kt
A hook that modifies the type of the "customPrefs" property in "DisplayPreferencesDto" to fix a nullability issue. In the 10.7 API specification the value of the map is incorrectly labelled as not-null. This hook changes the type to the exact type emitted from the 10.8 alpha API specification.
**This change needs to be reverted when the SDK starts using the 10.8 API specification.**
=> Add DisplayPreferencesDtoNullabilityFixHook

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/client/extensions/ApiClientExtensions.kt, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/sockets/SocketSubscription.kt, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/sockets/WebSocketApi.kt
Preparations for upcoming SocketApi pull request. This one deprecates to old API.
The aim is to remove it completely after 1.2.0 (so probably 1.3 or 1.4).
=> Deprecate WebSocketApi

samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/Options.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Bitrate.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Libraries.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Login.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Observe.kt
Wanted to implement this for a while now...
- Support `--username` and `--password` (optional) in kotlin-cli commands as replacement for `--token`
- When token is not supplied it will sign in to retrieve a token
This is useful for testing various functions of the SDK, like the WebSockets via the observe command using Gradle (`gradlew :samples:kotlin-cli:run --args="observe --server https://demo.jellyfin.org/stable --username demo"`).
=> Support username and password arguments in kotlin-cli sample

jellyfin-core/api/android/jellyfin-core.api, jellyfin-core/src/androidMain/kotlin/org/jellyfin/sdk/JellyfinOptions.kt
It still defaults to an automatic implementation which is the recommended way to use it.
=> Allow custom device info in Android target

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/ApiClient.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/MissingBaseUrlException.kt
A client often catches the generic ApiClientException when using the API. In some cases the base url might be unset.
This PR adds a new MissingBaseUrlException that is used now. Just like we do for user id's with the MissingUserIdException.
=> Add MissingBaseUrlException to replace IllegalArgumentException

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/SocketInstance.kt
Locking the updateConnectionState functions prevents duplicate calls to reconnect when registering multiple listeners at once.
=> Add mutex for updateConnectionState to prevent unneccesary reconnects

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/SocketInstance.kt
Was considering using the "ERROR" state but when we do that the SDK doesn't allow a call to "updateCredentials()" anymore.
=> Don't throw when baseUrl not set in SocketInstance

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/sockets/OkHttpWebsocketSession.kt, jellyfin-core/src/androidMain/kotlin/org/jellyfin/sdk/JellyfinOptions.kt, jellyfin-core/src/jvmMain/kotlin/org/jellyfin/sdk/JellyfinOptions.kt
Unfortunately the Ktor WebSocket implementation causes exceptions that we're unable to catch when the socket connection ends abruptly (e.g. jellyfin server stopping, network going offline etc.).
The OkHttp implementation does not have this issue, so it's going to be the default, with a fallback to Ktor for "multiplatform" support.
Required for #361
=> Add OkHttpWebsocketSession for JVM and Android targets

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/util/ApiSerializer.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/hooks/model/DisplayPreferencesDtoNullabilityFixHook.kt
- Remove useless `@OptIn(ExperimentalStdlibApi::class)` from DisplayPreferencesDtoNullabilityFixHook
- Move `@OptIn(InternalSerializationApi::class)` to functions that require it in ApiSerializer
=> Update @OptIn annotations

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/SocketInstance.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/SocketInstanceConnection.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/helper/ReconnectHelper.kt, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/sockets/OkHttpWebsocketSession.kt
Fixes #361 
This PR adds automatic reconnection abilities to the WebSocket code. It's fairly simple for now; retry 5 times when a disconnect/error occurs. Error will wait 30 seconds before retrying while a "normal" disconnect retries after 5. The algorithm could definitely be improved in the future, but  this will do for now.
=> Add retry logic to SocketInstance

openapi-generator/build.gradle.kts
Because someone decided to change the structure of the openapi files again.... Not changing the CI for this one though so if we decide to keep doing SDK beta releases for server beta's we need to do it manually.
draft because no merge until 1.2.0 is ready
=> Add generator task for stable-pre openapi files

openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiTypeBuilder.kt
Support empty schema in the OpenAPI generator. This will use the "JsonElement" type for empty schema's. An empty schema basically means "everything valid JSON is fine" [^1]. This is required for jellyfin/jellyfin#7561.
draft because no merge until 1.2.0 is ready
[^1]: http://json-schema.org/understanding-json-schema/basics.html#id1
=> Use JsonElement type for empty schema

jellyfin-model/src/commonMain/kotlin/org/jellyfin/sdk/model/ServerVersion.kt, jellyfin-model/src/commonTest/kotlin/org/jellyfin/sdk/model/discovery/ServerVersionTests.kt
This issue causes the RecommendedServerDiscovery to reject 10.8 servers.. oops
=> Fix ServerVersion comparison failing when build is not set

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/extensions/UserApiExtensions.kt
`val response by api.userApi.authenticateWithQuickConnect(QuickConnectDto(secret))`
vs
`val response by api.userApi.authenticateWithQuickConnect(secret)`
=> Add extension function for authenticateWithQuickConnect that takes the secret directly

build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt
I believe this should fix the issue where Renovate can't find androidx dependencies
=> Move dependency repository definition to build.gradle.kts

jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt
Discovered the issue when I tried the new client log endpoint and the logs were posted as a JSON string. Looking further I noticed that binary data (image uploads) didn't work either.
=> Fix invalid string and binary request bodies

.github/workflows/sdk-unstable-branch.yaml, .github/workflows/sdk-update-api-spec.yaml, openapi-generator/build.gradle.kts
Like always, testing CI is hard so I have no idea if this is going to work. If it does, this should fix the CI sometimes skipping the apiDump task.
=> Set input/output in openapi-generator tasks

jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/Jellyfin.kt
10.8.1 will add a few changes to the newly introduced Splashscreen API. One of these changes is the possibility to disable the splashscreen completely. This adds a new (not-null) boolean property called `splashscreenEnabled` to the `BrandingOptions` model which is a breaking change. Therefor we'll increase the minimum supported Jellyfin version in a patch update.
The removed import is because the annotation is imported by default and was no longer needed.
=> Increase minimum supported Jellyfin version to 10.8.1

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/ClientLogApi.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/hooks/HooksModule.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/hooks/api/ClientLogOperationUrlHook.kt
For ATV we're not using the SDK to send crash reports, it caches the URL instead and manually creates a connection when a crash occurs. With this change we don't need to add the path to the upload endpoint to the ATV code.
=> Generate URL builder function for ClientLogApi.logFile

jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt
This exception occurs for me when the server is unreachable, I'm mapping it to `TimeoutException` as it's the general type for network issues.
=> Map java.net.ConnectException to TimeoutException

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/RawResponse.kt, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt, jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/discovery/RecommendedServerDiscovery.kt
This fixes the TooGenericExceptionCaught linter issue. We ignored it, but it actually ended up causing issues. When a coroutine is cancelled it often throws a CancellationException. This was caught and converted to an ApiClientException causing coroutine cancellation to stop working. This change removes the places that catch Throwable, and they may throw exceptions now. We'll need to watch this and possibly add new catch branches later.
Fixes https://github.com/jellyfin/jellyfin-androidtv/issues/1909
Fixes https://github.com/jellyfin/jellyfin-androidtv/issues/1889
=> Remove catching (too generic) Throwable exceptions

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/util/AuthorizationHeaderBuilder.kt, jellyfin-api/src/commonTest/kotlin/org/jellyfin/sdk/api/client/util/AuthorizationHeaderBuilderTests.kt
10.8 finally has proper parsing for the Authorization header (https://github.com/jellyfin/jellyfin/pull/4799) so now we can finally support device names with special characters.
Fixes https://github.com/jellyfin/jellyfin-androidtv/issues/1946
=> Use URL encoding for authorization header values

jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/DeviceProfile.kt, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/TranscodingProfile.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/extra/defaultValueExtensions.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/model/ObjectModelBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiModelBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/ObjectApiModelProperty.kt
Right now this adds a few booleans/numbers to some response models - nothing fancy. This change is a part of #454 though, where we need the default values generated for request models.
The DefaultValueHook is not supported for models right now.
=> Support default values in generated models

openapi-generator/src/main/kotlin/org/jellyfin/openapi/Generator.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/MainModule.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/Verification.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/ContextBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/ApiClientExtensionsBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/ApisBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/extra/defaultValueExtensions.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/model/ModelsBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiApiServicesBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiConstantsBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiDefaultValueBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiModelBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiModelsBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/DefaultValue.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/GeneratorContext.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/GeneratorResult.kt
- Add generator context
This is a class containing the generated sources in various phases. The context is passed to various builders that need it to either add or read data from it.
- Add DefaultValue.EnumMember
Required for #463. Allows the default value of a property to be an enum member. This needed a type lookup and that's why we now have the context.
=> Support enum defaults, add generator context

jellyfin-core/src/androidMain/AndroidManifest.xml
This permission is left-over from the previous apiclient where it was needed to store credential information.
READ_EXTERNAL_STORAGE permission is no longer used so it can be removed.
Closes #472
=> Remove READ_EXTERNAL_STORAGE permission

.github/workflows/sdk-docs.yaml, .github/workflows/sdk-lint.yaml, .github/workflows/sdk-publish.yaml, .github/workflows/sdk-test.yaml, .github/workflows/sdk-unstable-branch.yaml, .github/workflows/sdk-update-api-spec.yaml
The gradle-build-action is used to setup CI for Gradle usage and contains better caching capabilities compared to the setup java action.
Also make logs less verbose by removing the --info option
=> Use gradle/gradle-build-action in CI

.github/workflows/sdk-docs.yaml, .gitignore, docs/guide/getting-started.md, docs/guide/websockets.md, docs/migration/v1.2.md
Also fixes some dead links (that caused CI to fail 😉) and rewrite the existing sdk-docs workflow.
How it works:
- Build Dokka and Vitepress in their own jobs with no references to GH pages. Upload build output as a zip
- Download artifacts from Dokka and Vitepress and put in a directory, upload as GH Pages artifact and deploy
Considerations:
- Vitepress doesn't like being in a directory by default so we need to add a custom domain or change the configuration
=> Build and deploy Vitepress documentation to GitHub pages

README.md
User documentation is moved to our website kotlin-sdk.jellyfin.org. Rewrite the README to explain how to develop for the SDK instead.
=> Rewrite README to focus on SDK developers instead of users

.github/workflows/sdk-unstable-branch.yaml, .github/workflows/sdk-update-api-spec.yaml
I've honestly no idea why the current approach doesn't work (because it should) but while testing in my fork this new approach seemed to work 🤞.
=> Split openapi generator and api dump tasks to avoid build failure

jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/discovery/AddressCandidateHelper.kt, jellyfin-core/src/jvmTest/kotlin/org/jellyfin/sdk/discovery/DiscoveryServiceTests.kt
- Empty input returned "http://" as candidate, which obviously is invalid
- Invalid port caused an exception
Both now return 0 candidates, added unit tests to verify.
Fixes #460
=> Fix AddressCandidateHelper issues with empty input and invalid ports

jellyfin-core/api/android/jellyfin-core.api, jellyfin-core/api/jvm/jellyfin-core.api, jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/discovery/AddressCandidateHelper.kt, jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/discovery/DiscoveryService.kt, jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/discovery/RecommendedServerDiscovery.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Discover.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Ping.kt
**Improve RecommendedServerDiscovery speed significantly**
Two changes to make it faster:
1. Lower "server not available" timeout from 5 to 3.5 seconds
2. Query 3 candidates simultaneously using a semaphore
Also removed the flow usage and just use a collection now, the flow didn't make much sense anyway. This doesn't break the ATV app and I expect other clients will be fine too.
=> Improve RecommendedServerDiscovery speed significantly

jellyfin-core/src/androidMain/kotlin/org/jellyfin/sdk/android/AndroidDevice.kt
Fixes jellyfin/jellyfin-android#794, not backporting since the stable android release uses an outdated SDK anyway.
=> Fallback to manufacturer + model when device name is null

jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/info/ApiConstants.kt, jellyfin-model/api/jellyfin-model.api, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/ClientCapabilitiesDto.kt, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/MediaStreamType.kt, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/OpenLiveStreamDto.kt, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/PlaybackInfoDto.kt, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/QueueRequestDto.kt, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/SetRepeatModeRequestDto.kt, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/SetShuffleModeRequestDto.kt, openapi.json
Same as #520 but for the release branch.
The only change is the new "DATA" member in the "MediaStreamType" enum.
=> Update OpenAPI to 10.8.5

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/util/AuthorizationHeaderBuilder.kt, jellyfin-api/src/commonTest/kotlin/org/jellyfin/sdk/api/client/util/AuthorizationHeaderBuilderTests.kt
Reported on Telegram/[Reddit](https://www.reddit.com/r/jellyfin/comments/ypcvwf/jellyfin_for_android_tv_crashing/). Caused app crashes when device name was used in legacy apiclient.
I don't think this necessarily fixes the issue because this changes the SDK only, but it's still good to escape newlines.
=> Remove linebreaks in AuthorizationHeaderBuilder.encodeParameterValue

.gitignore, docs/guide/getting-started.md, docs/migration/v1.4.md
- Use code-group in getting-started and v1.4 migration pages
Looks a lot better, see screenshots
- Add Vitepress cache to gitignore
I think this dir was added in one of the recent updates
Before
After
=> Use code-group in getting-started and v1.4 migration pages

jellyfin-model/api/jellyfin-model.api, jellyfin-model/src/commonMain/kotlin/org/jellyfin/sdk/model/extensions/TicksExtensions.kt
Right now we have multiple places in jellyfin-androidtv that need to convert ticks->duration. It makes sense to move this to the SDK so SDK users don't need to add their own utility function for this.
=> Add extensions to Long, Int and Double to create Duration from ticks

jellyfin-model/api/jellyfin-model.api, jellyfin-model/src/commonMain/kotlin/org/jellyfin/sdk/model/extensions/TicksExtensions.kt
Follow up on #616, adds `inWholeTicks` to Duration.
=> Add Duration.inWholeTicks to convert a Duration to ticks

jellyfin-core/build.gradle.kts
Fixes compiler warning:
> WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
=> Configure core-android publishing

settings.gradle.kts
Fixes build warning:
> Project accessors enabled, but root project name not explicitly set for 'jellyfin-sdk-kotlin'. Checking out the project in different folders will impact the generated code and implicitly the buildscript classpath, breaking caching.
=> Set name of Gradle root project

gradle.properties, jellyfin-core/build.gradle.kts
Fixes compiler warning:
> w: Multiplatform/Android-V1-SourceSetLayout: Multiplatform/Android-V1-SourceSetLayout is deprecated. Use Multiplatform/Android-V2-SourceSetLayout instead. 
To enable Multiplatform/Android-V2-SourceSetLayout: put the following in your gradle.properties: 
kotlin.mpp.androidSourceSetLayoutVersion=2
>
> To suppress this warning: put the following in your gradle.properties:
kotlin.mpp.androidSourceSetLayoutVersion1.nowarn=true
There's not much to change because the changes mainly apply to Android test sourcesets which we don't have. The manifest location we used is now a default path though, so that's nice.
=> Migrate to new Kotlin Multiplatform source set layout

openapi-generator/src/main/kotlin/org/jellyfin/openapi/MainModule.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/cli/MainCommand.kt
The option disable all hooks by unloading the Koin hooks module
=> Add command line option to disable hooks in openapi-generator

renovate.json
This should add the `npm` label to the Vitepress PR's
=> Extend organization Node.js Renovate config

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/ApiClient.kt, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt
Right now it was always set to `*/*`, which worked fine. But I wanted a constant so I can use the exact same value in Glide requests in jellyfin-androidtv.
=> Explicitly set Accept header in KtorClient

samples/java-cli/src/main/java/org/jellyfin/sample/cli/Main.java
This fixes the builds of the unstable branch because the "password" parameter is removed from the AuthenticateUserByName request.
=> Update java-cli sample to use UserApiExtensionsKt

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/HttpClientOptions.kt
Seeing a lot of users running on slow hardware getting hit by the 10 second timeout in the latest Android TV release, which migrated a bunch of stuff to the SDK. Increased the timeout to the 30 seconds that the old Java apiclient used. We'll need to revisit this number when the server database stuff is rewritten.
=> Increase default socket timeout value to 30 seconds

.github/workflows/gradlew-validate.yaml, .github/workflows/sdk-docs.yaml, .github/workflows/sdk-lint.yaml, .github/workflows/sdk-publish.yaml, .github/workflows/sdk-test.yaml, .github/workflows/sdk-unstable-branch.yaml, .github/workflows/sdk-update-api-spec.yaml
As requested.
Supersedes #690 
actions/checkout `ac59398` -> `24cb908`
Supersedes #689 
github/codeql-action `16964e9` -> `168b99b`
Supersedes #688 
actions/configure-pages `fc89b04` -> `7110e9e`
Supersedes #687 
peter-evans/create-pull-request `2b011fa` -> `38e0b6e`
Supersedes #686 
actions/deploy-pages `497da40` -> `7fec4b2`
Additionally bumps [gradle/wrapper-validation-action to v1.0.6](https://github.com/gradle/wrapper-validation-action/releases/tag/v1.0.6)
=> Update and specify full action versions

openapi-generator/build.gradle.kts, openapi-generator/src/main/kotlin/org/jellyfin/openapi/Generator.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/MainModule.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/cli/CompareCommand.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/compare/InfoComparator.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/compare/ModelComparator.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/compare/OperationComparator.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/compare/iterableExtensions.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/compare/model/CompareCollectionDiff.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/compare/model/CompareModel.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/compare/model/CompareModelConstant.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/compare/model/CompareModelProperty.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/compare/model/CompareOperation.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/compare/model/CompareOperationParameter.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/compare/model/CompareResult.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/compare/model/CompareValueDiff.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/compare/reporter/CompareReporter.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/compare/reporter/JsonCompareReporter.kt
I made this months ago but never finished the markdown reporter. So here is everything except the markdown reporter which I'll finish soon ©️.
Right now we're checking the OpenAPI difference in the server repo to help avoid breaking API changes. The tool we use is not perfect and the comments are pretty much unreadable. Thus my idea to do it myself was born. The new subcommand of the openapi-generator is called "compare" and it takes in 2 OpenAPI files and calculated the difference between them. It re-uses our existing code to parse an OpenAPI schema to our intermediate representation and then calculates all differences.
Some use-cases for this tool are:
- View API changes in server pull requests
- Create API changelogs for server releases
- [example JSON report between 10.8.9 and …
=> Add compare command to openapi-generator

gradle/libs.versions.toml
Current stable version of IntelliJ only supports 7.4.0-beta02 or lower. The next version (which will likely release in a few weeks) will support 7.4.2 so we can revert this PR when that happens.
=> Downgrade AGP to IntelliJ compatible 7.4.0-beta02

jellyfin-core/build.gradle.kts, jellyfin-core/src/androidMain/AndroidManifest.xml
- Migrate Android namespace to build file
- Remove deprecated target SDK
Android libraries don't use the value, property will be removed in AGP9
=> Migrate Android namespace to build file, remove deprecated target SDK

gradle/libs.versions.toml, jellyfin-core/build.gradle.kts
We don't use the androidx libraries so we can safely drop them from the build.
supersedes #706
=> Remove unused androidx libraries

.github/workflows/sdk-update-api-spec.yaml
Not exactly sure why it started failing but the content was a bit redundant with GitHub already showing the affected file count in a tab when viewing the PR.
=> Remove affected files from automated OpenAPI spec update pull request body

gradle/libs.versions.toml, jellyfin-api-ktor/api/jellyfin-api-ktor.api, jellyfin-api-ktor/build.gradle.kts, jellyfin-api-ktor/src/commonMain/kotlin/org/jellyfin/sdk/api/ktor/KtorClient.kt, jellyfin-api-ktor/src/jvmMain/kotlin/org/jellyfin/sdk/api/ktor/KtorClient.kt, jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/SocketInstance.kt, jellyfin-core/build.gradle.kts, jellyfin-core/src/androidMain/kotlin/org/jellyfin/sdk/JellyfinOptions.kt, jellyfin-core/src/jvmMain/kotlin/org/jellyfin/sdk/JellyfinOptions.kt, settings.gradle.kts
The jellyfin-api module currently hard-depends on Ktor which makes it hard to use, for example, okhttp 5. This is the initial PR to splitting the HTTP implementation to a separate package. We still have some parts of the code depending on Ktor (like the AuthorizationHeaderBuilder, UrlBuilder and de ByteReadChannel we use for binary responses in the generated API's) which will be fixed in upcoming pull requests.
The jellyfin-core module now also depends on jellyfin-api-ktor so for SDK users nothing will change.
=> Split KtorClient to separate module

openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/extra/defaultValueExtensions.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/model/ObjectModelBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/model/RequestModelBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiModelBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/ObjectApiModelProperty.kt
- Add support for schema properties with readOnly set to true and a default value
- They will be generated as class property so the serializer will add them and the deserializer ignores them
- Value can be read by SDK users
- Will be used for polymorphic discriminator values
This is needed to fully support jellyfin/jellyfin#9682. Sample output: https://github.com/nielsvanvelzen/jellyfin-sdk-kotlin/commit/73ae6251e6cb304f76bee1ebf2992b698a09ab80
Diff for KeepAliveMessage:
```diff
@@ -14,9 +14,10 @@ public data class KeepAliveMessage(
*/
@SerialName("Data")
public val `data`: Int,
+) : InboundWebSocketMessage, OutboundWebSocketMessage {
/**
* The different kinds of messages that are used in the WebSocket api.
*/
@SerialName("MessageType")
-       public override val messageType: …
```
=> Support readOnly properties in OpenAPI generator

openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/model/ObjectModelBuilder.kt
This fixes an issue where kotlinx.serialization would try to add the discriminator twice (once by library and once due to our definition)
=> Don't add @SerialName annotation to polymorphic discriminator property in ObjectModelBuilder

package.json
Only supports ESM now but the default in esbuild is commonjs
=> Fix Vitepress builds

jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/util/UrlBuilder.kt, jellyfin-api/src/commonTest/kotlin/org/jellyfin/sdk/api/client/util/UrlBuilderTests.kt
Sometimes you have a string that you don't fully trust and want to build a URL with it. To prevent this string from causing issues there needs to be a way to disable path templates, that way no matter what characters it contains it shouldn't throw an error while keeping the other benefits of the URL builder like properly adding the base URL, fixing double slashes and adding query parameters.
This change is especially useful when working with the `transcodingUrl` returned by the server to construct a URL for the transcoded media.
API changed in a backwards-compatible way.
=> Add ignorePathParameters option to UrlBuilder

.github/workflows/sdk-publish.yaml
(already cherrypicked to release branch)
GitHub broke stuff
=> Remove release environment from sdk-publish.yaml

jellyfin-model/api/jellyfin-model.api, jellyfin-model/src/commonMain/kotlin/org/jellyfin/sdk/model/deviceprofile/CodecProfileBuilder.kt, jellyfin-model/src/commonMain/kotlin/org/jellyfin/sdk/model/deviceprofile/ContainerProfileBuilder.kt, jellyfin-model/src/commonMain/kotlin/org/jellyfin/sdk/model/deviceprofile/DeviceProfileBuilder.kt, jellyfin-model/src/commonMain/kotlin/org/jellyfin/sdk/model/deviceprofile/DeviceProfileBuilderDsl.kt, jellyfin-model/src/commonMain/kotlin/org/jellyfin/sdk/model/deviceprofile/DirectPlayProfileBuilder.kt, jellyfin-model/src/commonMain/kotlin/org/jellyfin/sdk/model/deviceprofile/ProfileConditionsBuilder.kt, jellyfin-model/src/commonMain/kotlin/org/jellyfin/sdk/model/deviceprofile/SubtitleProfileBuilder.kt, jellyfin-model/src/commonMain/kotlin/org/jellyfin/sdk/model/deviceprofile/TranscodingProfileBuilder.kt
This change adds builders for the device profile and related classes. All DLNA only properties are hidden in the builders as they have no value for clients using this SDK.
I didn't feel like writing a documentation page (for now) so that might (or might not) come in a future PR.
Closes #131
=> Add builders for device profile and related models

jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/AudioApi.kt, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/DynamicHlsApi.kt, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/UniversalAudioApi.kt, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/VideosApi.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiApiServicesBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/RegexValidation.kt
Jellyfin 10.8.13 introduces some security fixes that restrict the various codec parameters used in the API. This was done using regular expressions that are also added to the OpenAPI specification.
This pull request uses those regex patterns to also validate them client-side to get faster feedback with invalid requests. Just like the previously added IntRangeValidation.
=> Add RegexValidation to OpenAPI generator

buildSrc/src/main/kotlin/Properties.kt, jellyfin-api-ktor/build.gradle.kts, jellyfin-api/build.gradle.kts, jellyfin-core/build.gradle.kts, jellyfin-model/build.gradle.kts, testutils/build.gradle.kts
Fixes Android support (our apps are built for Java 8)
=> Lower Java toolchain version to 8

.github/workflows/sdk-unstable-branch.yaml, .github/workflows/sdk-update-api-spec.yaml
Currently the unstable branch is not running because it is failing, so I disabled it over 8 months ago. This is not ideal as I normally use the diff to keep an eye on API changes, I prefer reading them in Kotlin instead of JSON.
This PR changes the workflows to ignore the failure of the `apiDump` task, committing code that will fail to build and when pushed, fails various CI tasks. It does allow me to use the unstable branch for diffing though.
=> Ignore failure of apiDump task in OpenAPI update workflows

openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiTypeBuilder.kt
The jellyfin-model module does not have a dependency on Ktor. If the binary type was used in a model it would use the ByteReadChannel class as type, causing a compiler error.
This change updates the OpenApiTypeBuilder to only use ByteReadChannel for operation return types.
=> Only use ByteReadChannel for API responses

openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/api/OperationParameterModelBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiApiServicesBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/compare/OperationComparator.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/ApiServiceOperation.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/ApiServiceOperationRequestBody.kt
I was working on support for multipart / formdata in request bodies but it ended up being extremely difficult with how models are currently generated. One part of this change was to make OperationBuilder aware of the request body type. The changes for this makes the code slightly better as it replaces string usages with types in some places so I thought it was worth something to keep.
Perhaps in the future I'll attempt the form support again and this would make it a bit easier to get started again.
=> Add type to make generator aware of operation request body type

jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/Jellyfin.kt
10.9 spec requires a 10.9 server
=> Increase minimum supported Jellyfin version to 10.9.0

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/util/ApiSerializer.kt
This pull request updates the JSON options in the ApiSerializer to more easily deal with new enum members and removed properties. I've added comments to the properties explaining why we're setting their values.
The useArrayPolymorphism option is removed because it is already disabled by default, it just enabled an old (obsolete) polymorphism implementation in the kotlinx.serialization library.
With this change we can more easily add new enum members if the properties using the enum has a default value. It does not work if the property is nullable without a default value though.
=> Update JSON options in ApiSerializer

jellyfin-model/api/jellyfin-model.api, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/DlnaProfileType.kt, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/ExternalIdMediaType.kt, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/GeneralCommandType.kt, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/HardwareEncodingType.kt, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/ImageFormat.kt, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/ItemFields.kt, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/MediaStreamType.kt, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/SeriesStatus.kt, openapi.json
**Note: Targets release-1.4.z branch**
When using a 10.8.z based SDK with a 10.9 server there are a few issues, all listed in the [10.9 on Android support issue](https://github.com/jellyfin/jellyfin-androidtv/issues/3467). While most problems can be fixed server-side, a few need changes in the SDK. More specifically: new enum members. When the SDK receives a response and expects an enum, an unknown member will cause deserialization issues.
This change adds all the new enum members from 10.9 to the 10.8.13 API specification. This prevents the deserialization issue and therefor allows a client to support both 10.8 and 10.9, although without the 10.9 specific features as those API's are not in the SDK.
By introducing this change in a 1.4 patch release we can have a smooth transition to 10.9 …
=> [1.4] Backport 10.9 enum changes to 10.8.13 API specification

jellyfin-api-ktor/api/jellyfin-api-ktor.api, jellyfin-api-ktor/src/commonMain/kotlin/org/jellyfin/sdk/api/ktor/KtorClient.kt, jellyfin-api-ktor/src/jvmMain/kotlin/org/jellyfin/sdk/api/ktor/KtorClient.kt, jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/ApiClient.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/MissingUserIdException.kt, jellyfin-core/api/android/jellyfin-core.api, jellyfin-core/api/jvm/jellyfin-core.api, jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/Jellyfin.kt, jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/util/ApiClientFactory.kt, samples/kotlin-cli/src/main/kotlin/org/jellyfin/sample/cli/command/Libraries.kt
We removed the "DefaultUserIdHook" in #879. At that time I left the userId property in ApiClient but we don't actually use it in the SDK itself. As such it could be removed entirely.
=> Remove userId property from ApiClient

jellyfin-api-ktor/api/jellyfin-api-ktor.api, jellyfin-api-ktor/src/jvmMain/kotlin/org/jellyfin/sdk/api/ktor/KtorClient.kt, jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/ApiClient.kt
I've been working on a new WebSocket client implementation for some weeks now and updating credentials for the socket has always been annoying (you need to manually call an `updateCredentials()` function).
This pull request adds the initial changes required to fix this problem. The update function will make the websocket  (if active) reconnect in my wip branch. The property setters are deprecated and should be removed in 1.6.
The reason for adding an update function instead of doing it from the setters it that in most cases you will be updating multiple properties at the same time, which would cause the WebSocket connection to initiate a reconnect multiple times if no extra code was added to prevent that.
Depends on #910
=> Replace property setters in ApiClient with new update function

jellyfin-core/src/jvmCommonMain/kotlin/org/jellyfin/sdk/discovery/LocalServerDiscovery.kt
Although most clients probably set the context already, it's good to have it safe by default. Discovery is a blocking operation and we want to make sure it is running on the IO dispatcher.
=> Flow on Dispatchers.IO by default in LocalServerDiscovery

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/exception/ssl/HandshakeCertificateException.kt
This extra `*` causes Android Studio to render a markdown list item.
=> Fix a kdoc typo

jellyfin-api-ktor/build.gradle.kts, jellyfin-api/build.gradle.kts, jellyfin-core/build.gradle.kts, jellyfin-model/build.gradle.kts
Maven Central requires this name or it will reject publishing. Ask me how I know.
=> Fix javadoc using wrong name

jellyfin-core/src/jvmTest/kotlin/org/jellyfin/sdk/api/SSLResolverTests.kt
The SSLResolverTests use the network (specifically badssl.com) and this results in flaky tests. They are currently failing in CI (See #930). Disable them for now.
=> Disable flaky unit tests

jellyfin-api-ktor/src/jvmMain/kotlin/org/jellyfin/sdk/api/ktor/KtorClient.kt, jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/ImageApi.kt, jellyfin-model/api/jellyfin-model.api, jellyfin-model/src/commonMain/kotlin/org/jellyfin/sdk/model/FileInfo.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiApiServicesBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/constants/Classes.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/constants/Types.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/ApiServiceOperationRequestBody.kt
Starting with Jellyfin 10.9 the server does some additional validation on image uploads. It now requires a `Content-Type` header in the request that contains the media type for one of the supported image formats.
The SDK never bothered with that and always told the server it was uploading binary data (`application/octet-stream`). While this is technically correct, the server does not like it anymore. Causing the API to reject all image uploads made using the SDK.
To fix this issue I've added a new model type called `FileInfo`. This model contains the bytes and an media type. The media type defaults to `application/octet-stream`, which obviously does not work for images.
To upload an image you'll need to convert the ByteArray to a FileInfo object. There are two ways to do this:
1. …
=> Support media type for image uploads

openapi-generator/build.gradle.kts
We recently changes all the paths in repo.jellyfin.org but the old ones kept working for a bit. Now that those are removed the OpenAPI updating no longer works because I forgot to update it here.
- Update URL for OpenAPI sources
- Remove support for "stable-pre" flavor as we no longer have pre-releases
=> Update URL for OpenAPI source

jellyfin-model/api/jellyfin-model.api, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/SeriesTimerInfoDto.kt, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/TimerInfoDto.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/hooks/HooksModule.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/hooks/model/LiveTVModelsHook.kt
I found some issues with the OpenAPI specification while migrating the Android TV app to the SDK. More specifically, the Live TV timer types have properties that should be nullable but are not.
The Live TV API uses the timer DTO's for creating, updating and reading. In the old java apiclient we only required the program id. Now the channelId, keepUntil, startDate, endDate, priority and status properties are also expected. My best guess is that swashbuckle is making some mistake because all of those types are not primitives (GUID/DateTime/Enum) so it probably skips checking for nullability?
Either way, this is a quickfix so the SDK is correct. We should fix this properly in 10.10.
=> Add LiveTVModelsHook

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/DefaultSocketApi.kt
The WebSocket API is not supposed to leak "low-level" implementation details like the keep alive functionality. There are two message types we can receive from the server, ForceKeepAlive and the "normal" KeepAlive. We did exclude the first but the latter was missing. Updated the filter to fix that.
=> Filter out all keep alive messages from WebSocket API

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/util/UrlBuilder.kt
We already have a DateTimeSerializer for the JSON bodies, but when sending a datetime via query parameter we should also make sure to include the timezone.
=> Fix LocalDateTime in URLBuilder missing timezone

jellyfin-model/src/jvmMain/kotlin/org/jellyfin/sdk/model/serializer/DateTimeSerializer.kt, jellyfin-model/src/jvmTest/kotlin/org/jellyfin/sdk/model/serializer/DateTimeSerializerTests.kt
The `ZonedDateTime.parse().toLocalDateTime()` approach would ignore timezone information from the timestamp and consider it local time. So if the server answers with UTC+2 and you are in UTC+5 the timestamp would be off by 3 hours.
Using `ZonedDateTime.parse().withZoneSameInstant().toLocalDateTime()` fixes this behavior.
Ideally we'd stop using LocalDateTime in the SDK and use ZonedDateTime but that's too big of a change to backport to the 1.5.z branch. I'll likely migrate to kotlinx-datetime later.
=> Fix timezone offset in DateTimeSerializer deserialization

jellyfin-model/src/jvmMain/kotlin/org/jellyfin/sdk/model/serializer/DateTimeSerializer.kt, jellyfin-model/src/jvmMain/kotlin/org/jellyfin/sdk/model/serializer/UUIDSerializer.kt
The kotlinx.serialization library added a new UUID serializer in 1.7.2 for the (experimental) UUID type in the Kotlin stdlib. Unfortunately this causes an issue, their serializer uses the same (simple-)name as ours, causing an exception when trying to encode/decode JSON.
The fix is two-sides, they'll fix their side to use more strict name validation. And we'll fix it to use a more unique name. On the upside, this will also improve the experience for users of the SDK, as they will also be less likely to have a serializer with a name we also use.
=> Prefix descriptor names of custom serializers

jellyfin-core/src/androidMain/kotlin/org/jellyfin/sdk/android/AndroidDevice.kt
We should also check if the string returned from `Settings.Global.DEVICE_NAME` is not blank.
The Jellyfin server requires a non-empty device name: 
```
System.ArgumentException: The value cannot be an empty string. (Parameter 'request.DeviceName')
```
This seems like a rare issue but I have at least one report in Findroid.
Downstream issue: https://github.com/jarnedemeulemeester/findroid/issues/846
=> Check if Android device name is not blank

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/DefaultSocketApi.kt
Whenever the socket connection is disconnected we automatically reconnect when there's still active subscriptions.
The reconnect function will always disconnect any existing connection before opening a new one.
Now guess what can go wrong: whenever you reconnect, it will trigger the automatic reconnect. This will cause a reconnection loop. This issue could be triggered in the ATV app by changing users, where it updates the credentials and a reconnect is attempted.
The fix was easy, never initiate the automatic reconnect when an reconnect is already happening.
Fixes jellyfin/jellyfin-androidtv#4225
=> Fix race condition in DefaultSocketApi causing disconnection loop when changing credentials

jellyfin-core/api/android/jellyfin-core.api, jellyfin-core/api/jvm/jellyfin-core.api, jellyfin-core/build.gradle.kts, jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/discovery/AddressCandidateHelper.kt, jellyfin-core/src/jvmCommonMain/kotlin/org/jellyfin/sdk/discovery/AddressCandidateHelper.kt, jellyfin-core/src/jvmTest/kotlin/org/jellyfin/sdk/discovery/DiscoveryServiceTests.kt
- Split AddressCandidateHelper into expect & actual
- Drop the public PROTOCOL_HTTP and PROTOCOL_HTTPS constants as they're not meant for library users
- Move from Ktor URL to OkHTTP HttpUrl class
- Drop direct ktor dependency from core module
The only behavior change that came up is that inputted IPv6 addresses are not shortened, which IMO is a good thing.
=> Use OkHTTP in AddressCandidateHelper

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/util/UrlBuilder.kt, jellyfin-api/src/commonTest/kotlin/org/jellyfin/sdk/api/client/util/UrlBuilderTests.kt
Similar to #1048. Updates the UrlBuilder to use OkHttp's HttpUrl. Unfortunately OkHttp does not expose its escaping functions so I had to implement my own for the path building. Small behavior change here is that we'll now escape slightly more characters by default, for which I had to update one unit test.
=> Use OkHTTP in UrlBuilder

jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/util/AuthorizationHeaderBuilder.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/util/UrlBuilder.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/util/url.kt
- Extract encodeURLPart, isUnreserved and extractQuerystring to internal functions in org.jellyfin.sdk.api.client.util package.
- Rename encodeURLPathPart to encodeURLPart
- Use encodeURLPart in AuthorizationHeaderBuilder
- Fix encoding of non-ascii characters (thanks for the unit testing with kanji)
=> Use encodeURLPart in AuthorizationHeaderBuilder

gradle/libs.versions.toml, jellyfin-api-ktor/src/jvmMain/kotlin/org/jellyfin/sdk/api/ktor/KtorClient.kt, jellyfin-api/api/jellyfin-api.api, jellyfin-api/build.gradle.kts, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/AudioApi.kt, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/ConfigurationApi.kt, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/DynamicHlsApi.kt, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/HlsSegmentApi.kt, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/ImageApi.kt, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/LibraryApi.kt, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/LiveTvApi.kt, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/MediaInfoApi.kt, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/PluginsApi.kt, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/SubtitleApi.kt, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/TrickplayApi.kt, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/UniversalAudioApi.kt, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/VideoAttachmentsApi.kt, jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/VideosApi.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/RawResponse.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/util/ApiSerializer.kt, jellyfin-api/src/commonTest/kotlin/org/jellyfin/sdk/api/client/util/ApiSerializerTests.kt, jellyfin-api/src/commonTest/kotlin/org/jellyfin/sdk/api/client/util/RawResponseTests.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiReturnTypeBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiTypeBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/constants/Types.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/hooks/api/BinaryOperationUrlHook.kt
- Use ByteArray instead of ByteReadChannel in RawResponse
- Move non-json decoding from ApiSerializer to RawResponse
- Update ApiSerializer.decodeResponseBody to receive string input
- Update api generator to use ByteArray instead of ByteReadChannel for binary responses
- Remove ktor dependency on jellyfin:api module
(ByteReadChannel is a Ktor type)
=> Use ByteArray instead of ByteReadChannel in API responses

jellyfin-api-okhttp/api/jellyfin-api-okhttp.api, jellyfin-api-okhttp/build.gradle.kts, jellyfin-api-okhttp/src/jvmMain/kotlin/org/jellyfin/sdk/api/okhttp/OkHttpClient.kt, jellyfin-api-okhttp/src/jvmMain/kotlin/org/jellyfin/sdk/api/okhttp/OkHttpFactory.kt, jellyfin-api-okhttp/src/jvmMain/kotlin/org/jellyfin/sdk/api/okhttp/OkHttpSocketConnection.kt, jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/client/ApiClientFactory.kt, jellyfin-api/src/jvmMain/kotlin/org/jellyfin/sdk/api/sockets/OkHttpSocketConnection.kt, jellyfin-core/api/android/jellyfin-core.api, jellyfin-core/api/jvm/jellyfin-core.api, jellyfin-core/build.gradle.kts, jellyfin-core/src/androidMain/kotlin/org/jellyfin/sdk/JellyfinOptions.kt, jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/JellyfinOptions.kt, jellyfin-core/src/jvmMain/kotlin/org/jellyfin/sdk/JellyfinOptions.kt, settings.gradle.kts
When the initial code for our Kotlin SDK was made I opted to use Ktor as this made it easy to get started. From the start we've used the OkHttp implementation and barely used Ktor functionality. Our WebSocket implementation already uses OkHttp and recent pull requests changed our URL building code to also use OkHttp.
With this change our default HTTP API networking implementation will also be OkHttp, Ktor will no longer be shipped by default. The Ktor module will be removed in a future release.
The implementation uses a single OkHttpFactory by default. This makes sure that all instances created share a connection pool and dispatcher, which is a best practice for performance according to OkHttp developers.
**Changes**
- Add new jellyfin-api-okhttp module
- Add OkHttpClient implementation …
=> Add OkHttpClient

jellyfin-model/api/jellyfin-model.api, jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/MediaStream.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/builder/openapi/OpenApiModelBuilder.kt, openapi-generator/src/main/kotlin/org/jellyfin/openapi/model/GeneratorContext.kt
The audioSpatialFormat property in MediaStream was considered static by the generator because it has readOnly set to true. This is not the desired behavior and was a bug in the generator.
This PR updates the generator to not set static based on the class schema but when the interface is referencing it. It should be static when the property name is the same as the polymorphic discriminator and there is a default value set.
=> Only mark polymorphic discriminators as static

.github/workflows/sdk-docs.yaml, .github/workflows/sdk-lint.yaml, .github/workflows/sdk-publish.yaml, .github/workflows/sdk-test.yaml, .github/workflows/sdk-unstable-branch.yaml, .github/workflows/sdk-update-api-spec.yaml, jellyfin-api-ktor/build.gradle.kts, jellyfin-api-okhttp/build.gradle.kts, jellyfin-api/build.gradle.kts, jellyfin-core/build.gradle.kts, jellyfin-model/build.gradle.kts, testutils/build.gradle.kts
At the moment the build chain uses an ancient version of the JVM Toolchain.
That causes issues for people with JDK versions any higher then 8.
This likely will cause issues with the automated build process on github.
@nielsvanvelzen 🫶 🗿
=> Update JVM toolchain to 21

jellyfin-api-ktor/src/jvmMain/kotlin/org/jellyfin/sdk/api/ktor/KtorClient.kt, jellyfin-api-okhttp/api/jellyfin-api-okhttp.api, jellyfin-api-okhttp/src/jvmMain/kotlin/org/jellyfin/sdk/api/okhttp/OkHttpClient.kt, jellyfin-api-okhttp/src/jvmMain/kotlin/org/jellyfin/sdk/api/okhttp/OkHttpSocketConnection.kt, jellyfin-api/api/jellyfin-api.api, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/DefaultSocketApi.kt, jellyfin-api/src/commonMain/kotlin/org/jellyfin/sdk/api/sockets/SocketConnection.kt
This change was requested a few times in various places and will make it easier to debug requests from a specific (Kotlin SDK based) client in reverse proxy logs.
Looks like this:
```
User-Agent: Jellyfin Android TV/0.0.0-dev.1 via jellyfin-sdk-kotlin (OkHttp/4.12.0)
```
=> Set User-Agent for HTTP requests

build.gradle.kts
The Sonatype repositories have been deprecated for a while which I was not aware of, then suddenly our snapshot publishing started failing and I found this page: https://central.sonatype.org/news/20250326_ossrh_sunset/.
This PR updates the publishing URLs. Credentials have already been updated in the repository settings.
=> Publish to Maven Central via Sonatype Central

jellyfin-model/build.gradle.kts
This fixes jellyfin/jellyfin-androidtv#4827
=> Mark kotlinx.serialization.json as implementation

gradle.properties
Removed this earlier in the 1.7.0 development but it looks like this one is still needed for #1097, which reintroduces androidx libraries in the dependency chain.
=> Revert removal of android.useAndroidX=true Gradle property

build.gradle.kts, gradle/libs.versions.toml, jellyfin-api-ktor/build.gradle.kts, jellyfin-api-okhttp/build.gradle.kts, jellyfin-api/build.gradle.kts, jellyfin-core/build.gradle.kts, jellyfin-model/build.gradle.kts
Use the [Gradle plugin](https://github.com/xvik/gradle-animalsniffer-plugin) for [Animal Sniffer](https://github.com/mojohaus/animal-sniffer) with [Gummy Bears](https://github.com/open-toast/gummy-bears) to verify the SDK is compatible with Android apps using library desugaring and use API level 19 or newer.
=> Check API compatibility using Animal Sniffer
